// 12 seed recipes — enough to test the deck end-to-end

export const SEED_RECIPES = [
  {
    id: 'r1', title: 'Lemon Garlic Chicken Skillet', cuisine: 'American', skillLevel: 'beginner',
    prepMinutes: 10, cookMinutes: 25, servings: 2, avgRating: 4.6, totalRatings: 342,
    description: 'A weeknight anchor. Bright, garlicky, done in one pan.',
    dietaryFlags: ['gluten-free'], allergenWarnings: ['dairy'],
    ingredients: [
      { name: 'Chicken breast', quantity: 1, unit: 'lb', aisle: 'protein' },
      { name: 'Garlic', quantity: 4, unit: 'cloves', aisle: 'produce' },
      { name: 'Olive oil', quantity: 3, unit: 'tbsp', aisle: 'pantry' },
      { name: 'Lemon', quantity: 2, unit: 'count', aisle: 'produce' },
      { name: 'Butter', quantity: 2, unit: 'tbsp', aisle: 'dairy', subs: ['Olive oil', 'Ghee'] },
      { name: 'Parsley', quantity: 0.25, unit: 'cup', aisle: 'produce' },
    ],
    steps: [
      { order: 1, text: 'Pat chicken dry, season both sides with salt and pepper.', timerSeconds: null },
      { order: 2, text: 'Heat olive oil in large skillet over medium-high.', timerSeconds: 90 },
      { order: 3, text: 'Add chicken, cook undisturbed 5-6 min until golden.', timerSeconds: 360 },
      { order: 4, text: 'Flip, reduce heat, cook 4-5 min more.', timerSeconds: 300 },
      { order: 5, text: 'Add butter, minced garlic, lemon juice. Baste 1 min.', timerSeconds: 60 },
      { order: 6, text: 'Rest 3 min, top with parsley.', timerSeconds: 180 },
    ],
  },
  {
    id: 'r2', title: 'Spaghetti Carbonara', cuisine: 'Italian', skillLevel: 'intermediate',
    prepMinutes: 10, cookMinutes: 15, servings: 2, avgRating: 4.8, totalRatings: 1247,
    description: 'Silky, smoky, no cream. The Roman way.',
    dietaryFlags: [], allergenWarnings: ['dairy', 'gluten', 'eggs'],
    ingredients: [
      { name: 'Spaghetti', quantity: 8, unit: 'oz', aisle: 'grain' },
      { name: 'Eggs', quantity: 3, unit: 'count', aisle: 'dairy' },
      { name: 'Parmesan', quantity: 2, unit: 'oz', aisle: 'dairy' },
      { name: 'Pancetta', quantity: 4, unit: 'oz', aisle: 'protein', subs: ['Guanciale', 'Bacon'] },
    ],
    steps: [
      { order: 1, text: 'Salt pasta water heavily. Bring to boil, add pasta.', timerSeconds: 600 },
      { order: 2, text: 'Render pancetta in cold skillet over medium until crisp.', timerSeconds: 480 },
      { order: 3, text: 'Whisk eggs, parmesan, black pepper.', timerSeconds: null },
      { order: 4, text: 'Reserve 1 cup pasta water. Drain, add pasta to pancetta off heat.', timerSeconds: null },
      { order: 5, text: 'Pour egg mix in slowly, tossing. Loosen with pasta water.', timerSeconds: 120 },
      { order: 6, text: 'Plate. Top with parmesan and pepper.', timerSeconds: null },
    ],
  },
  {
    id: 'r3', title: 'Spiced Chickpea Stew', cuisine: 'Middle Eastern', skillLevel: 'beginner',
    prepMinutes: 8, cookMinutes: 22, servings: 3, avgRating: 4.5, totalRatings: 198,
    description: 'Deep, warming, vegan. Tuesday dinner elevated.',
    dietaryFlags: ['vegan', 'gluten-free'], allergenWarnings: [],
    ingredients: [
      { name: 'Chickpeas', quantity: 2, unit: 'can', aisle: 'pantry' },
      { name: 'Roma tomatoes', quantity: 4, unit: 'count', aisle: 'produce' },
      { name: 'Yellow onion', quantity: 1, unit: 'count', aisle: 'produce' },
      { name: 'Garlic', quantity: 3, unit: 'cloves', aisle: 'produce' },
      { name: 'Cumin', quantity: 2, unit: 'tsp', aisle: 'spice' },
      { name: 'Paprika', quantity: 1, unit: 'tsp', aisle: 'spice' },
      { name: 'Coconut milk', quantity: 1, unit: 'can', aisle: 'pantry', subs: ['Heavy cream'] },
    ],
    steps: [
      { order: 1, text: 'Dice onion. Saute in olive oil over medium until golden.', timerSeconds: 420 },
      { order: 2, text: 'Add garlic, cumin, paprika. Toast 30 sec.', timerSeconds: 30 },
      { order: 3, text: 'Add tomatoes. Cook until jammy.', timerSeconds: 480 },
      { order: 4, text: 'Stir in chickpeas and coconut milk. Simmer.', timerSeconds: 600 },
      { order: 5, text: 'Season. Serve with rice or bread.', timerSeconds: null },
    ],
  },
  {
    id: 'r4', title: 'Korean Beef Bulgogi', cuisine: 'Korean', skillLevel: 'intermediate',
    prepMinutes: 20, cookMinutes: 10, servings: 3, avgRating: 4.7, totalRatings: 567,
    description: 'Sweet-savory marinade, quick sear, max flavor.',
    dietaryFlags: [], allergenWarnings: ['soy', 'sesame'],
    ingredients: [
      { name: 'Flank steak', quantity: 1, unit: 'lb', aisle: 'protein' },
      { name: 'Soy sauce', quantity: 0.25, unit: 'cup', aisle: 'condiment' },
      { name: 'Garlic', quantity: 4, unit: 'cloves', aisle: 'produce' },
      { name: 'Ginger', quantity: 1, unit: 'tbsp', aisle: 'produce' },
      { name: 'Brown sugar', quantity: 2, unit: 'tbsp', aisle: 'pantry', subs: ['Honey'] },
      { name: 'Sesame oil', quantity: 1, unit: 'tbsp', aisle: 'condiment' },
      { name: 'Scallions', quantity: 3, unit: 'stalks', aisle: 'produce' },
    ],
    steps: [
      { order: 1, text: 'Freeze steak 20 min, slice paper-thin against grain.', timerSeconds: 1200 },
      { order: 2, text: 'Whisk soy sauce, garlic, ginger, sugar, sesame oil.', timerSeconds: null },
      { order: 3, text: 'Marinate beef 15 min.', timerSeconds: 900 },
      { order: 4, text: 'Sear in very hot skillet 60 sec per side.', timerSeconds: 120 },
      { order: 5, text: 'Top with scallions, serve over rice.', timerSeconds: null },
    ],
  },
  {
    id: 'r5', title: 'Shakshuka', cuisine: 'Middle Eastern', skillLevel: 'beginner',
    prepMinutes: 10, cookMinutes: 20, servings: 2, avgRating: 4.9, totalRatings: 892,
    description: 'Eggs poached in spiced tomato. Anytime.',
    dietaryFlags: ['vegetarian', 'gluten-free'], allergenWarnings: ['eggs'],
    ingredients: [
      { name: 'Roma tomatoes', quantity: 6, unit: 'count', aisle: 'produce' },
      { name: 'Eggs', quantity: 4, unit: 'count', aisle: 'dairy' },
      { name: 'Bell pepper', quantity: 1, unit: 'count', aisle: 'produce' },
      { name: 'Yellow onion', quantity: 1, unit: 'count', aisle: 'produce' },
      { name: 'Garlic', quantity: 3, unit: 'cloves', aisle: 'produce' },
      { name: 'Cumin', quantity: 1, unit: 'tsp', aisle: 'spice' },
      { name: 'Paprika', quantity: 1, unit: 'tsp', aisle: 'spice' },
    ],
    steps: [
      { order: 1, text: 'Saute diced onion and pepper in olive oil.', timerSeconds: 420 },
      { order: 2, text: 'Add garlic, cumin, paprika. 30 sec.', timerSeconds: 30 },
      { order: 3, text: 'Add crushed tomatoes, simmer until thick.', timerSeconds: 600 },
      { order: 4, text: 'Make wells, crack eggs in.', timerSeconds: null },
      { order: 5, text: 'Cover, cook until whites set, yolks jammy.', timerSeconds: 300 },
    ],
  },
  {
    id: 'r6', title: 'Thai Green Curry', cuisine: 'Thai', skillLevel: 'intermediate',
    prepMinutes: 15, cookMinutes: 25, servings: 3, avgRating: 4.6, totalRatings: 423,
    description: 'Creamy coconut, fragrant basil.',
    dietaryFlags: ['gluten-free'], allergenWarnings: ['fish'],
    ingredients: [
      { name: 'Chicken breast', quantity: 1, unit: 'lb', aisle: 'protein' },
      { name: 'Green curry paste', quantity: 3, unit: 'tbsp', aisle: 'pantry' },
      { name: 'Coconut milk', quantity: 1, unit: 'can', aisle: 'pantry' },
      { name: 'Fish sauce', quantity: 1, unit: 'tbsp', aisle: 'condiment', subs: ['Soy sauce'] },
      { name: 'Thai basil', quantity: 1, unit: 'cup', aisle: 'produce', subs: ['Italian basil'] },
      { name: 'Bell pepper', quantity: 1, unit: 'count', aisle: 'produce' },
      { name: 'Basmati rice', quantity: 1, unit: 'cup', aisle: 'grain' },
    ],
    steps: [
      { order: 1, text: 'Cook rice per package.', timerSeconds: 1200 },
      { order: 2, text: 'Slice chicken thin.', timerSeconds: null },
      { order: 3, text: 'Fry paste in coconut cream until fragrant.', timerSeconds: 120 },
      { order: 4, text: 'Add chicken, cook until opaque.', timerSeconds: 300 },
      { order: 5, text: 'Pour in coconut milk and fish sauce. Simmer.', timerSeconds: 600 },
      { order: 6, text: 'Add pepper, cook 3 min.', timerSeconds: 180 },
      { order: 7, text: 'Off heat, stir in basil. Serve over rice.', timerSeconds: null },
    ],
  },
  {
    id: 'r7', title: 'Peanut Sesame Noodles', cuisine: 'Chinese', skillLevel: 'beginner',
    prepMinutes: 10, cookMinutes: 10, servings: 2, avgRating: 4.4, totalRatings: 612,
    description: 'Cold noodles, rich peanut sauce.',
    dietaryFlags: ['vegan'], allergenWarnings: ['peanuts', 'soy', 'sesame', 'gluten'],
    ingredients: [
      { name: 'Spaghetti', quantity: 8, unit: 'oz', aisle: 'grain' },
      { name: 'Peanut butter', quantity: 0.33, unit: 'cup', aisle: 'pantry' },
      { name: 'Soy sauce', quantity: 3, unit: 'tbsp', aisle: 'condiment' },
      { name: 'Rice vinegar', quantity: 2, unit: 'tbsp', aisle: 'condiment', subs: ['White vinegar'] },
      { name: 'Sesame oil', quantity: 1, unit: 'tbsp', aisle: 'condiment' },
      { name: 'Garlic', quantity: 2, unit: 'cloves', aisle: 'produce' },
      { name: 'Scallions', quantity: 2, unit: 'stalks', aisle: 'produce' },
    ],
    steps: [
      { order: 1, text: 'Cook pasta, drain, rinse cold.', timerSeconds: 600 },
      { order: 2, text: 'Whisk PB, soy, vinegar, sesame oil, garlic.', timerSeconds: null },
      { order: 3, text: 'Thin with pasta water.', timerSeconds: null },
      { order: 4, text: 'Toss noodles, top with scallions.', timerSeconds: null },
    ],
  },
  {
    id: 'r8', title: 'Black Bean Quesadillas', cuisine: 'Mexican', skillLevel: 'beginner',
    prepMinutes: 5, cookMinutes: 12, servings: 2, avgRating: 4.3, totalRatings: 324,
    description: 'Quick, cheesy, pantry-raid friendly.',
    dietaryFlags: ['vegetarian'], allergenWarnings: ['dairy', 'gluten'],
    ingredients: [
      { name: 'Black beans', quantity: 1, unit: 'can', aisle: 'pantry' },
      { name: 'Cheese', quantity: 4, unit: 'oz', aisle: 'dairy' },
      { name: 'Tortillas', quantity: 4, unit: 'count', aisle: 'grain' },
      { name: 'Yellow onion', quantity: 0.5, unit: 'count', aisle: 'produce' },
      { name: 'Cumin', quantity: 0.5, unit: 'tsp', aisle: 'spice' },
      { name: 'Lime', quantity: 1, unit: 'count', aisle: 'produce' },
    ],
    steps: [
      { order: 1, text: 'Mash beans with cumin and onion.', timerSeconds: null },
      { order: 2, text: 'Spread on tortilla, top with cheese, fold.', timerSeconds: null },
      { order: 3, text: 'Cook in dry skillet 3 min per side.', timerSeconds: 360 },
      { order: 4, text: 'Cut into wedges, squeeze lime.', timerSeconds: null },
    ],
  },
  {
    id: 'r9', title: 'Roasted Veggie Grain Bowl', cuisine: 'Mediterranean', skillLevel: 'beginner',
    prepMinutes: 10, cookMinutes: 30, servings: 2, avgRating: 4.4, totalRatings: 276,
    description: 'Vibrant, nourishing, built from what you have.',
    dietaryFlags: ['vegan', 'gluten-free'], allergenWarnings: ['sesame'],
    ingredients: [
      { name: 'Basmati rice', quantity: 1, unit: 'cup', aisle: 'grain' },
      { name: 'Chickpeas', quantity: 1, unit: 'can', aisle: 'pantry' },
      { name: 'Bell pepper', quantity: 1, unit: 'count', aisle: 'produce' },
      { name: 'Yellow onion', quantity: 1, unit: 'count', aisle: 'produce' },
      { name: 'Olive oil', quantity: 3, unit: 'tbsp', aisle: 'pantry' },
      { name: 'Lemon', quantity: 1, unit: 'count', aisle: 'produce' },
      { name: 'Tahini', quantity: 2, unit: 'tbsp', aisle: 'condiment', subs: ['Greek yogurt'] },
    ],
    steps: [
      { order: 1, text: 'Heat oven to 425F. Start rice.', timerSeconds: 1200 },
      { order: 2, text: 'Toss chickpeas and veg with oil, salt, pepper.', timerSeconds: null },
      { order: 3, text: 'Roast until crisp and charred.', timerSeconds: 1500 },
      { order: 4, text: 'Whisk tahini, lemon, water for drizzle.', timerSeconds: null },
      { order: 5, text: 'Build bowls.', timerSeconds: null },
    ],
  },
  {
    id: 'r10', title: 'Chicken Fried Rice', cuisine: 'Chinese', skillLevel: 'beginner',
    prepMinutes: 10, cookMinutes: 15, servings: 2, avgRating: 4.5, totalRatings: 456,
    description: 'Leftover rice transformed.',
    dietaryFlags: [], allergenWarnings: ['eggs', 'soy', 'sesame'],
    ingredients: [
      { name: 'Basmati rice', quantity: 2, unit: 'cup', aisle: 'grain' },
      { name: 'Chicken breast', quantity: 0.5, unit: 'lb', aisle: 'protein' },
      { name: 'Eggs', quantity: 2, unit: 'count', aisle: 'dairy' },
      { name: 'Soy sauce', quantity: 2, unit: 'tbsp', aisle: 'condiment' },
      { name: 'Garlic', quantity: 2, unit: 'cloves', aisle: 'produce' },
      { name: 'Scallions', quantity: 3, unit: 'stalks', aisle: 'produce' },
      { name: 'Sesame oil', quantity: 1, unit: 'tsp', aisle: 'condiment' },
    ],
    steps: [
      { order: 1, text: 'Dice chicken, scramble eggs aside.', timerSeconds: null },
      { order: 2, text: 'Sear chicken in hot oil.', timerSeconds: 240 },
      { order: 3, text: 'Add garlic, 30 sec.', timerSeconds: 30 },
      { order: 4, text: 'Add cold rice, break up, fry crisp.', timerSeconds: 300 },
      { order: 5, text: 'Toss in eggs, soy, sesame oil, scallions.', timerSeconds: 60 },
    ],
  },
  {
    id: 'r11', title: 'Crispy Halloumi Bowl', cuisine: 'Mediterranean', skillLevel: 'beginner',
    prepMinutes: 10, cookMinutes: 15, servings: 2, avgRating: 4.5, totalRatings: 287,
    description: 'Squeaky, golden, quick.',
    dietaryFlags: ['vegetarian', 'gluten-free'], allergenWarnings: ['dairy'],
    ingredients: [
      { name: 'Halloumi', quantity: 8, unit: 'oz', aisle: 'dairy' },
      { name: 'Chickpeas', quantity: 1, unit: 'can', aisle: 'pantry' },
      { name: 'Roma tomatoes', quantity: 2, unit: 'count', aisle: 'produce' },
      { name: 'Olive oil', quantity: 3, unit: 'tbsp', aisle: 'pantry' },
      { name: 'Lemon', quantity: 1, unit: 'count', aisle: 'produce' },
    ],
    steps: [
      { order: 1, text: 'Slice halloumi 1/2 inch, pat dry.', timerSeconds: null },
      { order: 2, text: 'Sear in dry skillet over medium-high.', timerSeconds: 180 },
      { order: 3, text: 'Flip, sear other side.', timerSeconds: 180 },
      { order: 4, text: 'Toss chickpeas, tomato, oil, lemon.', timerSeconds: null },
      { order: 5, text: 'Plate with halloumi on top.', timerSeconds: null },
    ],
  },
  {
    id: 'r12', title: 'Tomato Basil Soup', cuisine: 'American', skillLevel: 'beginner',
    prepMinutes: 5, cookMinutes: 25, servings: 3, avgRating: 4.7, totalRatings: 389,
    description: 'Creamy, bright, grilled cheese bait.',
    dietaryFlags: ['vegetarian', 'gluten-free'], allergenWarnings: ['dairy'],
    ingredients: [
      { name: 'Roma tomatoes', quantity: 6, unit: 'count', aisle: 'produce' },
      { name: 'Yellow onion', quantity: 1, unit: 'count', aisle: 'produce' },
      { name: 'Garlic', quantity: 3, unit: 'cloves', aisle: 'produce' },
      { name: 'Olive oil', quantity: 2, unit: 'tbsp', aisle: 'pantry' },
      { name: 'Vegetable broth', quantity: 2, unit: 'cup', aisle: 'pantry' },
      { name: 'Heavy cream', quantity: 0.25, unit: 'cup', aisle: 'dairy', subs: ['Coconut cream'] },
      { name: 'Fresh basil', quantity: 0.5, unit: 'cup', aisle: 'produce' },
    ],
    steps: [
      { order: 1, text: 'Roast tomatoes, onion, garlic at 425F.', timerSeconds: 1500 },
      { order: 2, text: 'Blend with broth until smooth.', timerSeconds: null },
      { order: 3, text: 'Return to pot, stir in cream and basil.', timerSeconds: null },
      { order: 4, text: 'Simmer 5 min. Season.', timerSeconds: 300 },
    ],
  },
];
