#!/usr/bin/env python3
"""Write modern + regional + tiki + zero-proof cocktails to NDJSON files.
Replaces the 3 stalled agents. Recipes drawn from common-knowledge canon.
"""
import json
import os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))

def w(filename, recipes):
    path = os.path.join(OUT_DIR, filename)
    with open(path, 'w', encoding='utf-8') as f:
        for r in recipes:
            f.write(json.dumps(r, ensure_ascii=False) + '\n')
    print(f"wrote {len(recipes)} -> {filename}")

def cocktail(title, year=None, region=None, ingredients=None, instructions=None,
             contributor=None, story=None, glass="rocks", method="shaken",
             garnish=None, abv=22, alcoholic=True, source="Modern craft"):
    return {
        "title": title,
        "content_type": "cocktail" if alcoholic else "mocktail",
        "is_alcoholic": 1 if alcoholic else 0,
        "is_historic": 0,
        "source_book": source,
        "source_year": year,
        "source_region": region,
        "contributor_name": contributor,
        "contributor_story": story,
        "cuisine": "cocktail",
        "description": "",
        "servings": 1,
        "prep_minutes": 3,
        "cook_minutes": 0,
        "original_text": None,
        "modernized_text": None,
        "instructions": instructions or [],
        "ingredients": ingredients or [],
        "glass_type": glass,
        "method": method,
        "garnish": garnish,
        "abv_percent": abv,
    }

def ing(name, qty, unit="oz", aisle="bar"):
    return {"name": name, "quantity": qty, "unit": unit, "aisle": aisle}

# ============== TIKI ==============
tiki = [
    cocktail("Mai Tai", 1944, "Oakland, USA", contributor="Trader Vic Bergeron",
        story="Trader Vic claimed it in 1944 at his Oakland bar; Donn Beach disputed authorship. The name is from Tahitian 'maita'i' — the best.",
        glass="rocks", method="shaken", garnish="mint sprig + lime shell", abv=28, source="Trader Vic 1944",
        ingredients=[ing("aged Jamaican rum", 1), ing("aged Martinique rhum", 1), ing("orange curaçao", 0.5),
                     ing("orgeat syrup", 0.25, aisle="pantry"), ing("simple syrup", 0.25, aisle="pantry"),
                     ing("fresh lime juice", 1, aisle="produce")],
        instructions=["Shake hard with crushed ice 8 seconds", "Pour unstrained into a double rocks glass",
                      "Garnish with spent lime shell + mint sprig"]),
    cocktail("Zombie", 1934, "Hollywood, USA", contributor="Donn Beach",
        story="Donn Beach invented the Zombie at his Hollywood bar in 1934. Limited to 2 per customer because the original recipe carried 5+ oz of rum.",
        glass="collins", method="blended", garnish="mint sprig", abv=32, source="Donn Beach 1934",
        ingredients=[ing("Jamaican dark rum", 1.5), ing("Puerto Rican gold rum", 1.5),
                     ing("151 demerara rum", 1), ing("fresh lime juice", 0.75, aisle="produce"),
                     ing("Donn's Mix #1 (cinnamon-grapefruit)", 0.5, aisle="pantry"),
                     ing("falernum", 0.5), ing("pomegranate grenadine", 1, aisle="pantry"),
                     ing("Pernod or absinthe", 0.125), ing("Angostura bitters", 1, unit="dash")],
        instructions=["Blend with crushed ice 5 seconds", "Pour unstrained into chimney/Collins glass",
                      "Top with crushed ice", "Garnish with mint sprig"]),
    cocktail("Jungle Bird", 1978, "Kuala Lumpur, Malaysia", contributor="Aviary Bar, KL Hilton",
        story="Created at the KL Hilton Aviary Bar in 1978. Lay forgotten for 30 years until rescued by Jeff 'Beachbum' Berry in his 2002 book Intoxica!.",
        glass="rocks", method="shaken", garnish="pineapple wedge", abv=18, source="KL Hilton 1978",
        ingredients=[ing("Jamaican black rum", 1.5), ing("Campari", 0.75), ing("pineapple juice", 1.5, aisle="produce"),
                     ing("fresh lime juice", 0.5, aisle="produce"), ing("simple syrup", 0.5, aisle="pantry")],
        instructions=["Shake all ingredients with ice 10 seconds", "Strain over fresh ice in a rocks glass",
                      "Garnish with pineapple wedge"]),
    cocktail("Painkiller (Pusser's style)", 1971, "British Virgin Islands", contributor="Daphne Henderson, Soggy Dollar Bar",
        story="Created by Daphne Henderson at the Soggy Dollar Bar on Jost Van Dyke. Pusser's Rum trademarked the name in the 1980s and the official recipe requires Pusser's.",
        glass="collins", method="shaken", garnish="orange slice + nutmeg", abv=14,
        ingredients=[ing("dark navy rum", 2), ing("pineapple juice", 4, aisle="produce"),
                     ing("orange juice", 1, aisle="produce"), ing("cream of coconut", 1, aisle="bar")],
        instructions=["Shake all ingredients with ice", "Pour into Collins glass over fresh ice",
                      "Float fresh-grated nutmeg + orange slice"]),
    cocktail("Three Dots and a Dash", 1942, "Hollywood, USA", contributor="Donn Beach",
        story="Donn Beach named this for Morse code for 'V' (Victory) — created during WWII as a wartime tribute.",
        glass="tiki", method="shaken", garnish="cherry + 3 pineapple chunks", abv=24,
        ingredients=[ing("aged rhum agricole", 1.5), ing("aged Jamaican rum", 0.5),
                     ing("falernum", 0.5), ing("orange juice", 0.5, aisle="produce"),
                     ing("fresh lime juice", 0.5, aisle="produce"), ing("honey syrup", 0.25, aisle="pantry"),
                     ing("Angostura bitters", 1, unit="dash"), ing("orange bitters", 1, unit="dash")],
        instructions=["Shake hard with crushed ice", "Strain into tiki mug over crushed ice",
                      "Garnish with cherry stacked over 3 pineapple chunks (the 'V')"]),
    cocktail("Navy Grog", 1941, "Hollywood, USA", contributor="Donn Beach",
        story="Donn Beach's salute to the British Navy's daily rum ration — three rums + grapefruit, with a frozen cone of crushed ice.",
        glass="rocks", method="shaken", garnish="ice cone with straw", abv=28,
        ingredients=[ing("Jamaican dark rum", 0.75), ing("aged Demerara rum", 0.75),
                     ing("Puerto Rican white rum", 0.75), ing("fresh lime juice", 0.75, aisle="produce"),
                     ing("fresh grapefruit juice", 0.75, aisle="produce"), ing("honey syrup", 1, aisle="pantry"),
                     ing("club soda", 1, aisle="other")],
        instructions=["Shake all but soda with crushed ice", "Strain into double rocks", "Top with soda",
                      "Spear a cone of crushed ice on a straw and place atop the drink"]),
    cocktail("Hurricane", 1940, "New Orleans, USA", contributor="Pat O'Brien",
        story="Pat O'Brien's bar invented this in the 1940s to use up unwanted rum. Served in the iconic hurricane-lamp glass.",
        glass="hurricane", method="shaken", garnish="orange slice + cherry", abv=24,
        ingredients=[ing("dark rum", 2), ing("light rum", 2), ing("passion fruit syrup", 1, aisle="bar"),
                     ing("fresh lime juice", 1, aisle="produce"), ing("fresh orange juice", 1, aisle="produce"),
                     ing("simple syrup", 0.5, aisle="pantry"), ing("grenadine", 1, unit="dash", aisle="pantry")],
        instructions=["Shake all with ice", "Strain into hurricane glass over fresh ice",
                      "Garnish with orange slice and cherry"]),
    cocktail("Singapore Sling", 1915, "Singapore", contributor="Ngiam Tong Boon, Raffles Hotel",
        story="Created by bartender Ngiam Tong Boon at the Raffles Hotel Long Bar in 1915. The pink color let women drink it in public when straight gin was taboo.",
        glass="hurricane", method="shaken", garnish="cherry + pineapple", abv=18,
        ingredients=[ing("gin", 1.5), ing("cherry brandy (Heering)", 0.5),
                     ing("Bénédictine", 0.25), ing("Cointreau", 0.25), ing("pineapple juice", 4, aisle="produce"),
                     ing("fresh lime juice", 0.5, aisle="produce"), ing("grenadine", 0.25, aisle="pantry"),
                     ing("Angostura bitters", 1, unit="dash")],
        instructions=["Shake all with ice", "Strain into hurricane glass over fresh ice",
                      "Garnish with cherry and pineapple wedge"]),
    cocktail("Piña Colada", 1954, "San Juan, Puerto Rico", contributor="Ramón Marrero, Caribe Hilton",
        story="Created by Ramón 'Monchito' Marrero at the Caribe Hilton's Beachcomber Bar in 1954. Took 3 months of experimentation to perfect the foamy texture.",
        glass="hurricane", method="blended", garnish="pineapple wedge + cherry", abv=12,
        ingredients=[ing("white rum", 2), ing("cream of coconut", 2, aisle="bar"),
                     ing("pineapple juice", 3, aisle="produce")],
        instructions=["Blend all with crushed ice until smooth", "Pour into hurricane glass",
                      "Garnish with pineapple wedge and cherry"]),
    cocktail("Missionary's Downfall", 1937, "Hollywood, USA", contributor="Donn Beach",
        story="Donn Beach's frozen cocktail with peach + mint — light and dangerously easy to drink.",
        glass="coupe", method="blended", garnish="mint sprig", abv=18,
        ingredients=[ing("light rum", 1.5), ing("peach brandy", 0.5),
                     ing("fresh lime juice", 0.5, aisle="produce"), ing("honey syrup", 0.5, aisle="pantry"),
                     ing("pineapple chunks", 1, unit="cup", aisle="produce"), ing("fresh mint leaves", 8, unit="leaves", aisle="produce")],
        instructions=["Blend all with crushed ice 5-10 seconds", "Pour into coupe", "Garnish with mint sprig"]),
    cocktail("Fog Cutter", 1940, "Oakland, USA", contributor="Trader Vic",
        story="Trader Vic's three-spirit punch — rum, gin, brandy — finished with a sherry float. Vic warned: 'one is enough.'",
        glass="collins", method="shaken", garnish="orange slice + mint", abv=24,
        ingredients=[ing("light rum", 2), ing("brandy", 1), ing("gin", 0.5),
                     ing("fresh lemon juice", 2, aisle="produce"), ing("orange juice", 1, aisle="produce"),
                     ing("orgeat syrup", 0.5, aisle="pantry"), ing("amontillado sherry", 0.5, unit="oz", aisle="bar")],
        instructions=["Shake all but sherry with ice", "Strain into Collins glass over fresh ice",
                      "Float sherry on top", "Garnish with orange slice and mint"]),
    cocktail("Scorpion", 1953, "Oakland, USA", contributor="Trader Vic",
        story="Trader Vic's ceremonial bowl drink, designed for 4-6 to share around a flaming centerpiece.",
        glass="rocks", method="shaken", garnish="gardenia or mint", abv=22,
        ingredients=[ing("light rum", 2), ing("brandy", 1), ing("orange juice", 2, aisle="produce"),
                     ing("fresh lemon juice", 1.5, aisle="produce"), ing("orgeat syrup", 0.5, aisle="pantry")],
        instructions=["Shake hard with crushed ice", "Strain into double rocks over fresh ice",
                      "Garnish with mint or gardenia"]),
    cocktail("Dr. Funk", 1942, "Apia, Samoa", contributor="Dr. Bernhard Funk",
        story="Named for the German doctor who attended Robert Louis Stevenson in Samoa in the 1880s. Donn Beach popularized the recipe in the 1940s.",
        glass="rocks", method="shaken", garnish="lime wedge", abv=20,
        ingredients=[ing("aged Demerara rum", 1.5), ing("absinthe or pastis", 0.25),
                     ing("fresh lime juice", 0.75, aisle="produce"), ing("grenadine", 0.5, aisle="pantry"),
                     ing("simple syrup", 0.25, aisle="pantry"), ing("club soda", 1, aisle="other")],
        instructions=["Shake all but soda with crushed ice", "Pour into rocks glass", "Top with soda",
                      "Garnish with lime wedge"]),
    cocktail("Suffering Bastard", 1942, "Cairo, Egypt", contributor="Joe Scialom, Shepheard's Hotel",
        story="Created by Joe Scialom at Cairo's Shepheard's Hotel in 1942 to cure Allied soldiers' hangovers during WWII. Reportedly mixed by the gallon for the British 8th Army.",
        glass="collins", method="built", garnish="mint sprig + cucumber + orange slice", abv=18,
        ingredients=[ing("gin", 1), ing("brandy", 1), ing("fresh lime juice", 0.5, aisle="produce"),
                     ing("ginger beer", 4, aisle="other"), ing("Angostura bitters", 2, unit="dash")],
        instructions=["Build in Collins glass over ice", "Top with ginger beer", "Stir gently",
                      "Garnish with mint, cucumber and orange"]),
    cocktail("Painkiller (free-form)", region="Tiki revival", contributor="Pan-tree variant",
        story="Pan-tree's free-form take, no specific brand required.",
        glass="collins", method="shaken", garnish="nutmeg + orange", abv=14,
        ingredients=[ing("dark rum", 2), ing("pineapple juice", 4, aisle="produce"),
                     ing("orange juice", 1, aisle="produce"), ing("cream of coconut", 1, aisle="bar")],
        instructions=["Shake all with ice", "Pour over fresh ice in Collins glass",
                      "Float orange slice and grate fresh nutmeg over top"]),
]

# ============== ZERO-PROOF / MOCKTAILS ==============
zero = [
    cocktail("Virgin Mojito", region="Cuba (mocktail)", contributor=None,
        story="Lime, mint, sugar, and soda — the classic Cuban Mojito with the rum left out. Just as refreshing on a hot afternoon.",
        glass="collins", method="muddled", garnish="mint sprig + lime wheel", abv=0, alcoholic=False, source="Mocktail canon",
        ingredients=[ing("fresh lime juice", 1, aisle="produce"), ing("simple syrup", 0.75, aisle="pantry"),
                     ing("fresh mint leaves", 10, unit="leaves", aisle="produce"),
                     ing("club soda", 4, aisle="other")],
        instructions=["Muddle mint gently in Collins glass with lime juice and syrup",
                      "Fill with crushed ice", "Top with soda", "Garnish with mint sprig and lime wheel"]),
    cocktail("Seedlip Garden 108 & Tonic", 2015, "London, England", contributor="Ben Branson, Seedlip",
        story="The flagship serve from Seedlip, the world's first non-alcoholic distilled spirit, launched 2015 in London.",
        glass="copa", method="built", garnish="snap pea + mint", abv=0, alcoholic=False, source="Seedlip 2015",
        ingredients=[ing("Seedlip Garden 108 (or alt-gin)", 2, aisle="bar"),
                     ing("light tonic water", 4, aisle="other")],
        instructions=["Build over fresh ice in copa glass", "Stir gently", "Garnish with snap pea and mint"]),
    cocktail("Virgin Margarita", region="Mexico (mocktail)",
        story="The Margarita's lime and orange profile, alcohol-free.",
        glass="margarita", method="shaken", garnish="lime wheel + salt rim", abv=0, alcoholic=False, source="Mocktail canon",
        ingredients=[ing("fresh lime juice", 1.5, aisle="produce"), ing("fresh orange juice", 1, aisle="produce"),
                     ing("agave nectar", 0.75, aisle="pantry"), ing("club soda", 1, aisle="other")],
        instructions=["Salt the rim of a margarita glass", "Shake lime, orange, agave with ice",
                      "Strain into glass over ice", "Top with soda", "Garnish with lime wheel"]),
    cocktail("Cucumber Cooler", region="Modern garden",
        story="Cooling, gardenly, ten-second-make. The kind of drink you nurse on a porch.",
        glass="collins", method="muddled", garnish="cucumber slice", abv=0, alcoholic=False, source="Mocktail canon",
        ingredients=[ing("cucumber slices", 4, unit="slices", aisle="produce"),
                     ing("fresh lime juice", 0.75, aisle="produce"), ing("simple syrup", 0.5, aisle="pantry"),
                     ing("club soda", 5, aisle="other")],
        instructions=["Muddle cucumber in shaker", "Add lime + syrup + ice, shake 5s",
                      "Double-strain into Collins glass over ice", "Top with soda"]),
    cocktail("Blood Orange & Rosemary Spritz", region="Modern Italian style",
        story="A booze-free riff on the Italian aperitivo tradition. The rosemary turns a sweet juice into something grown-up.",
        glass="copa", method="built", garnish="rosemary sprig", abv=0, alcoholic=False, source="Modern mocktail",
        ingredients=[ing("fresh blood orange juice", 2, aisle="produce"),
                     ing("rosemary simple syrup", 0.5, aisle="pantry"),
                     ing("sparkling water", 4, aisle="other"), ing("Angostura bitters", 1, unit="dash")],
        instructions=["Build over ice in a wine glass", "Top with sparkling water",
                      "Slap rosemary sprig and add as garnish"]),
    cocktail("Watermelon Tajín Fizz", region="Mexico",
        story="Tajín — the chili-lime-salt seasoning — turns sweet watermelon into a savory-sour-spicy electric drink.",
        glass="rocks", method="shaken", garnish="Tajín rim + lime", abv=0, alcoholic=False, source="Modern mocktail",
        ingredients=[ing("fresh watermelon juice", 3, aisle="produce"),
                     ing("fresh lime juice", 0.75, aisle="produce"),
                     ing("Tajín seasoning", 1, unit="pinch", aisle="spice"),
                     ing("agave", 0.25, aisle="pantry"), ing("club soda", 1, aisle="other")],
        instructions=["Rim a rocks glass with Tajín", "Shake watermelon, lime, agave with ice",
                      "Strain into glass over fresh ice", "Top with soda", "Garnish with lime"]),
    cocktail("Pomegranate Rose Spritz", region="Modern garden",
        story="Rose water + pomegranate is one of those combinations that feels both ancient (Persian sherbet) and brand new.",
        glass="copa", method="built", garnish="rose petal", abv=0, alcoholic=False, source="Modern mocktail",
        ingredients=[ing("pomegranate juice", 2, aisle="produce"),
                     ing("rose water", 0.25, unit="tsp", aisle="bar"),
                     ing("fresh lime juice", 0.5, aisle="produce"),
                     ing("simple syrup", 0.25, aisle="pantry"),
                     ing("sparkling water", 4, aisle="other")],
        instructions=["Combine pomegranate, rose, lime, syrup in glass over ice",
                      "Top with sparkling water", "Garnish with edible rose petal"]),
    cocktail("Hibiscus Lemonade", region="Mexico (agua de jamaica style)",
        story="Agua de jamaica — the dried-hibiscus tea sold from glass barrels in every Mexican market — given a sour-cocktail twist.",
        glass="collins", method="built", garnish="lemon wheel + hibiscus flower", abv=0, alcoholic=False, source="Mocktail canon",
        ingredients=[ing("hibiscus tea (cold)", 4, aisle="other"),
                     ing("fresh lemon juice", 1, aisle="produce"),
                     ing("simple syrup", 0.75, aisle="pantry"),
                     ing("fresh mint leaves", 4, unit="leaves", aisle="produce")],
        instructions=["Combine all in Collins glass over ice", "Stir well", "Garnish with lemon wheel"]),
    cocktail("Espresso & Tonic", 2007, "Helsingborg, Sweden", contributor="Koppi Roasters",
        story="Started at Koppi Roasters in Sweden in 2007. A double shot of espresso poured slowly over tonic — the bitter-bright mash-up Instagram couldn't get enough of.",
        glass="rocks", method="built", garnish="orange peel", abv=0, alcoholic=False, source="Modern coffee",
        ingredients=[ing("tonic water", 5, aisle="other"),
                     ing("espresso (double shot)", 2, aisle="other"),
                     ing("simple syrup", 0.25, unit="tsp", aisle="pantry")],
        instructions=["Fill rocks glass with ice and tonic", "Pull double espresso fresh",
                      "Slowly pour espresso over the back of a spoon onto the tonic",
                      "Express orange peel"]),
    cocktail("Tepache", region="Mexico",
        story="A traditional Mexican fermented pineapple drink — sweet, tart, slightly fizzy. Sold from clay pots on Mexico City sidewalks for centuries.",
        glass="collins", method="built", garnish="cinnamon stick", abv=1, alcoholic=False, source="Mexican tradition",
        ingredients=[ing("tepache", 6, aisle="other"), ing("fresh lime juice", 0.5, aisle="produce")],
        instructions=["Pour tepache over ice in Collins glass", "Add lime juice", "Garnish with cinnamon stick"]),
]

# ============== GLOBAL REGIONAL ==============
regional = [
    cocktail("Ti' Punch", region="Martinique, French Caribbean",
        story="The national drink of Martinique. 'Ti' is short for 'petit'. Tradition says: chacun prépare sa propre mort — each prepares their own death — at the table by adjusting their own ratios.",
        glass="rocks", method="built", garnish=None, abv=42, source="Martinique tradition",
        ingredients=[ing("rhum agricole blanc", 2), ing("cane syrup", 0.25, aisle="pantry"),
                     ing("lime disc", 1, unit="piece", aisle="produce")],
        instructions=["Press lime disc and cane syrup in glass with bar spoon",
                      "Add rhum, stir briefly", "Serve neat or with one small cube"]),
    cocktail("Caipirinha", region="Brazil",
        story="Brazil's national cocktail. Cachaça — sugar-cane spirit fermented, not from molasses like rum — muddled with lime and sugar.",
        glass="rocks", method="muddled", garnish="lime wedge", abv=24, source="Brazilian canon",
        ingredients=[ing("cachaça", 2), ing("lime, quartered", 1, unit="piece", aisle="produce"),
                     ing("white sugar", 2, unit="tsp", aisle="pantry")],
        instructions=["Muddle lime and sugar in rocks glass", "Fill with crushed ice",
                      "Add cachaça, stir vigorously"]),
    cocktail("Pisco Sour", 1903, "Lima, Peru", contributor="Victor Vaughen Morris",
        story="Created by American bartender Victor Morris at the Morris' Bar in Lima around 1920. Both Peru and Chile claim the cocktail, but the Lima recipe with bitters atop the foam is the canonical version.",
        glass="coupe", method="shaken", garnish="3 dashes Angostura on foam", abv=20, source="Peru 1920",
        ingredients=[ing("pisco", 2), ing("fresh lime juice", 1, aisle="produce"),
                     ing("simple syrup", 0.75, aisle="pantry"), ing("egg white", 1, unit="piece", aisle="dairy"),
                     ing("Angostura bitters", 3, unit="dash")],
        instructions=["Dry-shake all but bitters (no ice) 10 seconds to build foam",
                      "Add ice, shake hard 15 seconds", "Strain into coupe",
                      "Drop 3 dashes of Angostura on the foam"]),
    cocktail("Aperol Spritz", 1950, "Padua, Italy", contributor="Aperol",
        story="The 3-2-1 spritz — three parts prosecco, two parts Aperol, one splash soda — was popularized by Aperol's marketing in the 2010s but the spritz tradition dates to Veneto in the 1800s.",
        glass="copa", method="built", garnish="orange slice", abv=11, source="Italian aperitivo",
        ingredients=[ing("Aperol", 2), ing("prosecco", 3, aisle="bar"),
                     ing("club soda", 1, aisle="other")],
        instructions=["Fill wine glass with ice", "Pour prosecco, then Aperol, then soda",
                      "Stir gently", "Garnish with orange slice"]),
    cocktail("Negroni Sbagliato", 1972, "Milan, Italy", contributor="Mirko Stocchetto, Bar Basso",
        story="Bar Basso's bartender Mirko Stocchetto reached for gin and grabbed prosecco by mistake — sbagliato means 'mistaken' in Italian. The mistake stuck.",
        glass="rocks", method="built", garnish="orange peel", abv=11,
        ingredients=[ing("Campari", 1), ing("sweet vermouth", 1), ing("prosecco", 1, aisle="bar")],
        instructions=["Build all in a rocks glass over a large ice cube",
                      "Stir briefly", "Express orange peel and drop in"]),
    cocktail("Garibaldi", region="Italy",
        story="Campari + fluffy fresh-squeezed orange juice. Named for Giuseppe Garibaldi, who unified Italy by joining the orange-rich south with Campari's northern home.",
        glass="collins", method="built", garnish="orange slice", abv=12,
        ingredients=[ing("Campari", 1.5), ing("fluffy fresh orange juice", 4, aisle="produce")],
        instructions=["Pour Campari over ice in Collins glass",
                      "Top with fluffy (high-speed-blended) fresh OJ", "Stir, garnish with orange slice"]),
    cocktail("Japanese Highball (Toki)", region="Japan",
        story="In Japan, the highball is a national obsession — Suntory's marketing turned it into the salaryman's drink. The serve is precise: hard ice, hard pour, hard stir.",
        glass="highball", method="built", garnish="lemon peel", abv=14, source="Japanese tradition",
        ingredients=[ing("Suntory Toki whisky", 1.5), ing("chilled club soda", 4.5, aisle="other")],
        instructions=["Fill chilled highball with ice", "Pour whisky", "Stir 13 times exactly to chill",
                      "Add fresh ice to top", "Pour soda down the spiral of a bar spoon",
                      "Stir 3.5 times", "Express lemon peel"]),
    cocktail("Caipiroska", region="Brazil/Russia hybrid",
        story="The Caipirinha's vodka cousin. Born in Brazil when locals ran out of cachaça during a 1990s shortage and reached for vodka.",
        glass="rocks", method="muddled", garnish="lime wedge", abv=22,
        ingredients=[ing("vodka", 2), ing("lime, quartered", 1, unit="piece", aisle="produce"),
                     ing("white sugar", 2, unit="tsp", aisle="pantry")],
        instructions=["Muddle lime and sugar in rocks glass", "Fill with crushed ice",
                      "Add vodka, stir vigorously"]),
    cocktail("Pisco Punch", 1855, "San Francisco, USA", contributor="Duncan Nicol, Bank Exchange Saloon",
        story="The Bank Exchange Saloon in San Francisco's Bohemian San Francisco served Pisco Punch by the bowl from 1855. The recipe was a closely guarded secret — Mark Twain raved about it.",
        glass="rocks", method="shaken", garnish="pineapple chunk", abv=18, source="SF 1855",
        ingredients=[ing("pisco", 2), ing("fresh lime juice", 0.5, aisle="produce"),
                     ing("pineapple syrup", 0.75, aisle="pantry"),
                     ing("pineapple chunks", 2, unit="chunks", aisle="produce")],
        instructions=["Shake all with ice", "Strain over fresh ice in rocks",
                      "Garnish with pineapple chunk"]),
    cocktail("Mezcal Negroni (Oaxaca Old Fashioned)", region="Mexico (modern)", contributor="Phil Ward, Death & Co",
        story="Phil Ward at Death & Co NYC subbed mezcal for whiskey in an Old Fashioned around 2007 — the smoky agave version became a definitive modern classic.",
        glass="rocks", method="stirred", garnish="orange peel", abv=32,
        ingredients=[ing("reposado tequila", 1.5), ing("mezcal", 0.5),
                     ing("agave nectar", 0.25, unit="tsp", aisle="pantry"),
                     ing("Angostura bitters", 2, unit="dash")],
        instructions=["Stir all with ice 30 seconds", "Strain over a large cube in rocks",
                      "Express orange peel"]),
    cocktail("Boulevardier", 1927, "Paris, France", contributor="Erskine Gwynne",
        story="Created by writer Erskine Gwynne in Paris around 1927 — he edited a Paris-based literary magazine called Boulevardier. Bourbon's answer to the Negroni.",
        glass="rocks", method="stirred", garnish="orange peel", abv=28,
        ingredients=[ing("bourbon or rye whiskey", 1.5), ing("Campari", 1), ing("sweet vermouth", 1)],
        instructions=["Stir all with ice 25 seconds", "Strain over a large cube in rocks",
                      "Express orange peel"]),
    cocktail("Vesper", 1953, "London, England", contributor="Ian Fleming",
        story="James Bond ordered this in Casino Royale (1953). Fleming wrote the recipe into Bond's mouth — and Bond drinks it 'shaken, not stirred.'",
        glass="coupe", method="shaken", garnish="lemon peel", abv=32,
        ingredients=[ing("gin", 3), ing("vodka", 1), ing("Lillet Blanc (or Cocchi Americano)", 0.5)],
        instructions=["Shake hard with ice 10 seconds", "Strain into chilled coupe",
                      "Express lemon peel"]),
    cocktail("Cuba Libre", 1900, "Havana, Cuba", contributor="American soldiers",
        story="Born in Havana around 1900 when American soldiers post-Spanish-American War mixed Bacardi rum with Coca-Cola and squeezed in a lime. Toast: 'Por Cuba libre!' — to a free Cuba.",
        glass="highball", method="built", garnish="lime wedge", abv=12,
        ingredients=[ing("white rum", 2), ing("Coca-Cola", 4, aisle="other"),
                     ing("fresh lime juice", 0.5, aisle="produce")],
        instructions=["Squeeze lime into highball over ice", "Add rum", "Top with cold Coca-Cola",
                      "Stir gently", "Garnish with lime wedge"]),
    cocktail("Caesar", 1969, "Calgary, Canada", contributor="Walter Chell",
        story="Created by Walter Chell at the Calgary Inn in 1969 to celebrate a new Italian restaurant. Canada's national cocktail. Roughly 350 million Caesars are consumed in Canada every year.",
        glass="highball", method="built", garnish="celery stalk + lime + Tajín rim", abv=10,
        ingredients=[ing("vodka", 1.5), ing("Clamato juice", 5, aisle="other"),
                     ing("Worcestershire sauce", 4, unit="dash", aisle="condiment"),
                     ing("hot sauce", 3, unit="dash", aisle="condiment"),
                     ing("celery salt", 1, unit="pinch", aisle="spice"),
                     ing("fresh lime juice", 0.5, aisle="produce")],
        instructions=["Rim highball with celery salt", "Build all over ice",
                      "Stir gently", "Garnish with celery stalk and lime wedge"]),
    cocktail("Paloma", 1950, "Mexico", contributor="Don Javier Delgado Corona",
        story="Mexico's most popular tequila cocktail, more loved at home than the Margarita. Often credited to Don Javier of La Capilla in Tequila, Jalisco.",
        glass="highball", method="built", garnish="lime wedge + salt rim", abv=12,
        ingredients=[ing("blanco tequila", 2), ing("fresh lime juice", 0.5, aisle="produce"),
                     ing("grapefruit soda (Squirt or Jarritos)", 4, aisle="other"),
                     ing("salt for rim", 1, unit="pinch", aisle="spice")],
        instructions=["Salt the rim of a highball glass", "Add ice, then tequila and lime",
                      "Top with grapefruit soda", "Garnish with lime wedge"]),
]

w('tiki.ndjson', tiki)
w('zero-proof.ndjson', zero)
w('global-regional.ndjson', regional)
print(f"\nTotal cocktails written: {len(tiki) + len(zero) + len(regional)}")
