package app.pantrie.feature.parties.game

/**
 * Interactive Mystery Night scripts. One GameScript per PartyMenu where
 * isMystery=true. When a host opens a game, the script gets sent to the
 * backend Durable Object as JSON, which then drives the beat-by-beat
 * dispatch across all connected phones.
 *
 * All five launch mysteries are fully authored to the design doctrine:
 * one-sentence twist beats, 1-3 word action labels, character objectives,
 * and a per-mystery cover_beat_library that the backend uses to fire
 * synchronized cover lines to every non-target player whenever a real
 * twist is dispatched. See memory/project_mystery_nights_design_doctrine.md.
 */

/**
 * Privacy doctrine read aloud by the host at T+0 before any beat fires.
 * Locks the rule of trust the rest of the design depends on. From the
 * audit Part 4.
 */
private const val PRIVACY_PREAMBLE =
  "Your dossier is yours. Your phone is yours. Anything that buzzes on it is yours to use, share, or keep. You may lie. You may bluff. You may invent. The only rule is that you do not show another guest your screen, you do not read another guest's dossier, and you only volunteer a secret when your phone tells you to or you choose to. The night is yours to play."

/** Return the canonical script for a given mystery menu, or null if not authored yet. */
fun scriptFor(menuId: String): GameScript? = when (menuId) {
  "murder_algonquin"      -> SCRIPT_MURDER_ALGONQUIN
  "bootleggers_wife"      -> SCRIPT_BOOTLEGGERS_WIFE
  "last_toast_ritz"       -> SCRIPT_LAST_TOAST_RITZ
  "heir_pendennis"        -> SCRIPT_HEIR_PENDENNIS
  "vanishing_socialite"   -> SCRIPT_VANISHING_SOCIALITE
  else -> null
}

// ---------------------------------------------------------------------------
//  Murder at the Algonquin — full interactive script.
//  90-minute three-hour game. 5 characters. ~18 beats including reveal.
//  Cast IDs are stable strings used by the DO to route targeted beats.
// ---------------------------------------------------------------------------

private val ALGONQUIN_CAST = listOf(
  GameCharacter(
    id = "the_playwright",
    name = "The Playwright",
    role = "A successful Broadway author, witty and openly competitive. Had a play savaged by the dead man six months ago and never forgave the review.",
    secret = "You returned to the hotel at midnight and saw the dead man arguing with someone in the lobby. You did not see the face.",
    objective = "Force the Critic's review of your play to be retracted publicly tonight. The Editor has the authority. Make him use it before the morning edition prints.",
  ),
  GameCharacter(
    id = "the_actress",
    name = "The Actress",
    role = "Recently passed over for a lead role the dead man championed for someone else. Drinks two Aviations in close succession at the start of the evening.",
    secret = "You knew the role would go to the other actress because the dead man told you privately last week, drunk, that the producer was leaning that way.",
    objective = "Keep the producer's name out of every conversation. He is your brother-in-law and you are not ready for that to be public.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_editor",
    name = "The Critic's Editor",
    role = "Edits the dead man's column at The Standard. Was planning to fire him next week. Has a soft spot for the actress.",
    secret = "You have the dead man's resignation letter, dated yesterday afternoon. He was leaving before you could fire him.",
    objective = "Surface the resignation letter at the right moment so The Standard does not look like it lost a man it was firing. Protect the Actress.",
  ),
  GameCharacter(
    id = "the_matron",
    name = "The Society Matron",
    role = "Hostess to half of New York. Knows everyone's secrets and is willing to deploy them. Holds the Round Table's purse strings on Tuesday nights.",
    secret = "You saw the dead man and the visiting author whispering in the corner after dinner. They did not see you.",
    objective = "Trade what you saw last night for a favor from someone at this table. You do not care which one. Leave with something owed to you.",
  ),
  GameCharacter(
    id = "the_author",
    name = "The Visiting Author",
    role = "Newly arrived from London with a new novel and a habit of disappearing at parties. Polite. Restrained. Watching everyone closely.",
    secret = "You knew the dead man from before. From a different life. You met to settle that history last night.",
    objective = "Avoid being identified before the reveal. If a guest gets close, plant the lapel pin under another guest's chair.",
    bluffs = listOf(
      "I was on the back stair to the cloakroom at ten-forty — I had torn my hem and was looking for a pin. The Maître d' would have heard me pass.",
      "Twelve years in London is twelve years too far back to remember. Who else here was in London in twelve?",
      "If anyone here has a motive worth naming, look at the Editor. He had a man to fire and a letter that made it impossible.",
    ),
  ),
  // ---- Optional extras. The mystery plays cleanly without these. ----
  GameCharacter(
    id = "the_columnist",
    name = "The Rival Columnist",
    role = "Writes the gossip column at The Daily Mirror. Resented the dead man's higher pay and his Algonquin seat.",
    secret = "You filed a column this morning that ran a paragraph about the dead man you cannot take back.",
    objective = "Find out whether the morning edition has hit newsstands yet. Buy back the column if it has not.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_understudy",
    name = "The Understudy",
    role = "Plays the Actress's understudy at the Lyceum. Was at last night's dinner because the Actress brought her.",
    secret = "The role the dead man championed for the other actress was meant to be auditioned by you in two weeks.",
    objective = "Stay quiet about your audition. Watch the Actress and the Editor for signs of what they knew.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_bellman",
    name = "The Bellman",
    role = "Worked the Algonquin lobby from eight until two last night. Carries every guest's secrets in his head.",
    secret = "You took three dollars from the Playwright at twelve-fifteen to forget what time he came in.",
    objective = "Collect what you are owed for what you saw. Do not name names without payment in hand.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_manager",
    name = "The Hotel Manager",
    role = "Runs the Algonquin. Wants this matter resolved before the morning papers print.",
    secret = "The dead man's key was returned to the front desk at twelve forty-five last night.",
    objective = "Steer the table to a name before midnight. The morning edition prints at four.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_photographer",
    name = "The Society Photographer",
    role = "Was at last night's dinner shooting plates for the Sunday society page.",
    secret = "One of last night's plates shows the Visiting Author leaving the dining room at ten-forty.",
    objective = "Decide whether the plate is worth more sold to a paper or used to settle a favor at this table.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_maitre",
    name = "The Maître d'",
    role = "Seats the Round Table every Tuesday. Knows the order of arrival to the minute.",
    secret = "The Visiting Author asked to be seated next to the dead man last night. She does not usually request seats.",
    objective = "Protect the Round Table's reputation. Volunteer nothing the room does not pull out of you.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_detective",
    name = "The Hotel Detective",
    role = "Algonquin staff. Discreet. Carries a notebook only the manager has ever read.",
    secret = "A torn lapel pin was found in the hallway carpet outside the dead man's door this morning.",
    objective = "Hand the pin to the right hand at the right moment. Keep the hotel's name off the front page.",
    is_optional = true,
  ),
)

/**
 * Cover beats for Murder at the Algonquin. Pulled at random and fired to every
 * non-target player at the same instant a real twist goes to the target,
 * so every phone vibrates together and observers cannot tell whose phone
 * holds the real information. Period-flavored throwaway lines, 5-10 second
 * reads. Doctrine: memory/project_mystery_nights_design_doctrine.md.
 */
private val ALGONQUIN_COVERS = listOf(
  "The waiter refills your glass without asking.",
  "The candle on your side of the table is burning down faster than the others.",
  "A draft from the hallway stirs the napkin in your lap.",
  "Across the room, a busboy drops a tray of glassware and the diners pretend not to hear.",
  "The pianist begins the second chorus of a Berlin song you do not quite recognize.",
  "Your cigarette case is almost empty.",
  "A woman two tables over looks at you for half a second too long, then looks away.",
  "The Algonquin's manager passes through the dining room without making eye contact.",
  "Your reflection in the silverware looks older than you remember.",
  "The bellman at the corner is reading a folded newspaper and only pretending.",
  "Someone you knew at school walks past with a woman you do not.",
  "The kitchen door swings open and the smell of onions and butter comes out with it.",
  "The clock above the bar is two minutes slow.",
  "The ice in your glass cracks quietly as it melts.",
  "Outside the window, a taxi horn sounds longer than it should.",
  "A telegram boy waits in the lobby. The doorman waves him off.",
  "Your shoe is pinching. You shift in your chair.",
  "The Matron's pearls catch the light in a way that draws every eye for a second.",
  "A coat is delivered to the table. It is not yours.",
  "The maître d' refills the water from a silver pitcher that does not match the table service.",
  "Two of the lamps along the back wall flicker in sequence, then steady.",
)

val SCRIPT_MURDER_ALGONQUIN = GameScript(
  total_duration_minutes = 90,
  cast = ALGONQUIN_CAST,
  cover_beat_library = ALGONQUIN_COVERS,
  privacy_preamble = PRIVACY_PREAMBLE,
  host_cues = HostCues(
    opening_monologue = "It is Tuesday evening, October 14, 1924, at the Algonquin. Last night the same five of you had dinner at this table with the theatre critic from The Standard. This morning he was found dead in his room upstairs. The Algonquin's manager has invited you back to sit where you sat last night and order what you ordered last night. The morning edition of every paper in this city prints at four o'clock. Before then, one of you is going to tell me what happened.",
    success_picture = "T+30: the lapel pin is in play and at least one player has named the Visiting Author aloud. T+60: the resignation letter has been read aloud and the table has split into two camps. T+80: the room is quiet, the Author is talking too much. If at T+60 the room is still chasing the Editor's letter, fire panic button #1.",
    panic_buttons = listOf(
      "Ask the Matron, out loud, what she saw in the side hallway after dinner last night.",
      "Walk over to the Author's chair. Stop. Look at her shoes. Walk away without speaking.",
      "Refill the Editor's glass. Ask him whose name was supposed to run in tomorrow's column.",
    ),
    post_game_prompts = listOf(
      "Each player: what did your character do at midnight when they left the dining room?",
      "Visiting Author: was twelve years long enough?",
      "Group photo at the table holding the lapel pin. One frame. No retakes.",
    ),
    recommended_cocktails = listOf("Aviation", "Sidecar", "Manhattan"),
  ),
  beats = listOf(
    // ---- T+0 / T+3: Openers ----
    GameBeat(0, "all", "NARRATIVE",
      "The Algonquin Hotel. October 14, 1924. The critic from The Standard is dead. One of you knows why.",
      host_note = "Read flat, almost bored. The room will lean in for you."),
    GameBeat(3, "all", "SYSTEM",
      "Round one is poured. Take your seat. Order what your character ordered last night."),

    // ---- T+5: Killer-first private acknowledgment ----
    GameBeat(5, "the_author", "TWIST",
      "You did it. Twelve years overdue. Survive eighty more minutes. Do not touch your lapel.",
      actions = listOf(
        GameBeatAction("steady", "Steady"),
        GameBeatAction("plan_bluff", "Plan a bluff"),
      ),
      host_note = "The only private confession the killer gets all night. Do not surface."),

    // ---- Optional staff openers ----
    GameBeat(6, "the_bellman", "TWIST",
      "The Playwright recognizes you. He looks down at his glass and waits for you to set the price.",
      actions = listOf(
        GameBeatAction("name_price", "Name price"),
        GameBeatAction("wait", "Wait"),
        GameBeatAction("warn_manager", "Warn Manager"),
      ),
      is_optional = true,
    ),
    GameBeat(8, "the_maitre", "TWIST",
      "Someone asks you who chose the seating last night. Choose your phrasing carefully.",
      actions = listOf(
        GameBeatAction("name_author", "Name Author"),
        GameBeatAction("blame_host", "Blame house"),
        GameBeatAction("deflect", "Deflect"),
      ),
      is_optional = true,
    ),

    // ---- T+10 / T+12: First private clues ----
    GameBeat(10, "the_playwright", "TWIST",
      "A bellman slips you a note: \"Seen returning at midnight. The lobby man forgets, for a price.\"",
      actions = listOf(
        GameBeatAction("pay_off", "Pay him"),
        GameBeatAction("ignore", "Ignore"),
        GameBeatAction("share", "Read aloud"),
      ),
    ),
    GameBeat(12, "the_editor", "TWIST",
      "The dead man's resignation letter is in your inside pocket, dated yesterday.",
      actions = listOf(
        GameBeatAction("produce_now", "Produce it"),
        GameBeatAction("wait", "Wait"),
        GameBeatAction("show_actress", "Show the Actress"),
      ),
    ),

    // ---- T+14: Playwright steps away to pay the bellman ----
    GameBeat(14, "the_playwright", "STEP_AWAY",
      "Excuse yourself to the lobby. Pay the bellman in cash. Stay gone four minutes. Return with the folded bill visible. Volunteer nothing.",
      host_note = "Pre-place a folded dollar at the lobby's front desk. He retrieves it now."),

    // ---- T+15: First CLOCK ----
    GameBeat(15, "all", "CLOCK",
      "Quarter past eight. The morning edition prints at four. You have seven and three quarters hours, and the manager is holding the front page open until you give him a name.",
      host_note = "Hold a beat after \"a name.\" Look around the table slowly."),

    // ---- T+20: Actress optional ----
    GameBeat(20, "the_actress", "TWIST",
      "The Matron mentions, low, that the dead man whispered with the Visiting Author after dinner.",
      actions = listOf(
        GameBeatAction("confront_author", "Confront her"),
        GameBeatAction("note", "Note it"),
        GameBeatAction("tell_playwright", "Tell the Playwright"),
      ),
      is_optional = true,
    ),

    // ---- T+25: The lapel pin lands ----
    GameBeat(25, "the_author", "TWIST",
      "The bellman hands you a velvet pouch from the hotel detective. Inside: your torn lapel pin. The Detective has not asked whose.",
      actions = listOf(
        GameBeatAction("pocket", "Pocket it"),
        GameBeatAction("drop_under_chair", "Plant it"),
        GameBeatAction("ask_who", "Ask aloud"),
      ),
    ),

    // ---- T+26: Author RECON to cloakroom ----
    GameBeat(26, "the_author", "RECON",
      "Excuse yourself to the cloakroom. Your coat is on the third hook. Three minutes.",
      host_note = "Pre-place the wrapping cloth from the bellman's pouch in her coat pocket. She finds it now and decides what to do with it."),

    // ---- T+28: Frame defense — paired to the lapel pin's plant ----
    GameBeat(28, "the_editor", "TWIST",
      "You feel something against your foot under the table. Probably nothing. The Author has been watching you for a minute.",
      actions = listOf(
        GameBeatAction("retrieve", "Reach down"),
        GameBeatAction("ignore", "Ignore"),
        GameBeatAction("accuse_aloud", "Accuse aloud"),
      ),
      host_note = "If the Author chose Plant at T+25, this is the real frame-up. If not, this is misdirection she can use."),

    // ---- T+30: Photographer BE_SEEN + optional Columnist ----
    GameBeat(30, "the_photographer", "BE_SEEN",
      "Stand. Carry the printed plate slowly past the Author's chair. Sit at the bar for thirty seconds. Return without speaking.",
      host_note = "Lower the lights a notch when she stands. Watch the Author's hands.",
      is_optional = true,
    ),
    GameBeat(30, "the_columnist", "TWIST",
      "A copyboy from the Mirror just rushed in. The morning edition went out an hour ago.",
      actions = listOf(
        GameBeatAction("recall", "Recall it"),
        GameBeatAction("own_it", "Own it"),
        GameBeatAction("blame_editor", "Blame Editor"),
      ),
      is_optional = true,
    ),

    // ---- T+30: CLOCK ----
    GameBeat(31, "all", "CLOCK",
      "Half past eight. The bellman has been carrying messages between three of you. The room is taller for it."),

    // ---- T+33: Optional Photographer ----
    GameBeat(33, "the_photographer", "TWIST",
      "The plate is in your bag. It catches the Visiting Author leaving the dining room at ten-forty.",
      actions = listOf(
        GameBeatAction("show_room", "Show the table"),
        GameBeatAction("offer_editor", "Offer Editor"),
        GameBeatAction("keep", "Keep it"),
      ),
      is_optional = true,
    ),

    // ---- T+35: Toast ----
    GameBeat(35, "all", "NARRATIVE",
      "The Editor raises a glass. \"To the man we are not mourning enough.\"",
      host_note = "Read with no irony. The Editor means it."),

    // ---- T+38: Matron's memory ----
    GameBeat(38, "the_matron", "TWIST",
      "You remember it now — he said \"twelve years is a long time to keep something quiet,\" and she replied too low to hear.",
      actions = listOf(
        GameBeatAction("raise_publicly", "Say it now"),
        GameBeatAction("trade_secret", "Trade it"),
        GameBeatAction("keep", "Keep it"),
      ),
    ),

    // ---- T+44: CLOCK ----
    GameBeat(44, "all", "CLOCK",
      "Quarter to nine. The Standard's editors are watching the wire. The Manager is watching the door. You are running out of conversation."),

    // ---- T+45: Manager optional ----
    GameBeat(45, "the_manager", "TWIST",
      "The morning edition prints at four. You need a name from this table before three.",
      actions = listOf(
        GameBeatAction("press_editor", "Press Editor"),
        GameBeatAction("press_matron", "Press Matron"),
        GameBeatAction("wait", "Wait"),
      ),
      is_optional = true,
    ),

    // ---- T+50: Playwright squeezed + Matron/Editor RENDEZVOUS ----
    GameBeat(50, "the_playwright", "TWIST",
      "The Editor slides the resignation letter across to you. His hand is shaking.",
      actions = listOf(
        GameBeatAction("read_aloud", "Read it aloud"),
        GameBeatAction("pocket_quiet", "Pocket it"),
        GameBeatAction("demand", "Demand names"),
      ),
    ),
    GameBeat(50, "the_matron", "RENDEZVOUS",
      "Excuse yourself to the dining-room doorway. The Editor will join you. Two minutes. Decide what you tell each other before you walk back.",
      host_note = "Paired beat — fires to the Editor at the same instant. Two empty chairs at once is the point."),
    GameBeat(50, "the_editor", "RENDEZVOUS",
      "Excuse yourself to the dining-room doorway. The Matron is already there. Two minutes. Decide what you tell each other before you walk back."),

    // ---- T+55: Detective + DEAD_DROP ----
    GameBeat(55, "the_detective", "TWIST",
      "The wrapping cloth from the pouch is in your inside pocket. There is a single dark hair caught in it.",
      actions = listOf(
        GameBeatAction("present_room", "Present it"),
        GameBeatAction("show_manager", "Show Manager"),
        GameBeatAction("hold", "Hold it"),
      ),
      is_optional = true,
    ),
    GameBeat(56, "the_detective", "DEAD_DROP",
      "Cross to the bar. As you pass the Author's chair, drop the cloth under it. Do not look back.",
      host_note = "This loops the frame-up back onto the framer. If the Author planted the pin, the Detective answers with the cloth.",
      is_optional = true,
    ),

    // ---- T+59: CLOCK ----
    GameBeat(59, "all", "CLOCK",
      "Nine o'clock. Last call on small talk. The manager returns in thirty minutes for a name."),

    // ---- T+60: Public pivot ----
    GameBeat(60, "all", "NARRATIVE",
      "The room quiets. The waiter pauses at the door, watching.",
      host_note = "Do not refill any glass for sixty seconds after you read this."),

    // ---- T+65: Author under pressure (3 options, not 4 — kill the pattern tell) ----
    GameBeat(65, "the_author", "TWIST",
      "Twelve years ago in London is back in the room.",
      actions = listOf(
        GameBeatAction("deflect_to_actress", "Accuse Actress"),
        GameBeatAction("deflect_to_editor", "Accuse Editor"),
        GameBeatAction("stay_silent", "Stay silent"),
      ),
    ),

    // ---- T+72: Optional Understudy ----
    GameBeat(72, "the_understudy", "TWIST",
      "The Actress just touched her glass to yours without looking — the cue you arranged at brunch.",
      actions = listOf(
        GameBeatAction("speak", "Speak now"),
        GameBeatAction("nod", "Nod back"),
        GameBeatAction("ignore", "Ignore"),
      ),
      is_optional = true,
    ),

    // ---- T+74: CLOCK ----
    GameBeat(74, "all", "CLOCK",
      "Quarter past nine. Fifteen minutes until the manager comes for a name. If you do not give him one, he gives them one."),

    // ---- T+75: Actress connects the dots (optional) ----
    GameBeat(75, "the_actress", "TWIST",
      "The producer's wife — the one who decided the casting — was the Visiting Author's sister.",
      actions = listOf(
        GameBeatAction("say_aloud", "Say aloud"),
        GameBeatAction("save_for_after", "Save it"),
      ),
      is_optional = true,
    ),

    // ---- T+80: Accusation ----
    GameBeat(80, "all", "NARRATIVE",
      "Make your accusation. Write a name on a slip and place it face-down at the table.",
      host_note = "Hand out slips and pens before you read this. Do not let anyone write before you have read it."),

    // ---- T+90: Reveal ----
    GameBeat(90, "all", "REVEAL",
      "It was the Visiting Author.\n\nTwelve years ago in London, the dead man — under a different name — had blackmailed her over a manuscript she had submitted under her sister's identity. She had paid him quarterly for a decade. When she heard he was coming to New York to retire, she came to confront him. She offered him the resignation letter, written under coercion, as a final clean-out. When he refused to leave town quietly, she returned to his room after dinner with a vial of digitalis hidden in her glove and poured it into his nightcap before she left.\n\nThe lapel pin was hers. The wrapping cloth held one of her hairs. The whispered conversation the Matron overheard was him refusing the offer. The Editor was about to fire a man who was about to vanish anyway. The Playwright saw her in the lobby at midnight, returning from his room. The Actress's chain of reasoning about the producer's wife is correct: the Visiting Author had every opportunity.\n\nIt was twelve years overdue.",
      killer_character_id = "the_author",
      ending_id = "blackmail_overdue",
      host_note = "Read paragraph one. Pause three seconds. Read paragraph two — at \"the wrapping cloth\" look at the Detective. Read paragraph three. Look at the Author before \"twelve years overdue.\""),
  ),
)

// ---------------------------------------------------------------------------
//  The Bootlegger's Wife — Chicago, 1929. Killer: the_partner.
// ---------------------------------------------------------------------------

private val BOOTLEGGER_COVERS = listOf(
  "Footsteps cross the floor above. Three pairs. Slow.",
  "The bartender wipes a glass with a cloth that smells of rye.",
  "Someone shifts on the bench at the far end and the wood groans.",
  "The boiler in the back room cycles on, then off.",
  "A draft from the alley door brings in the smell of wet brick.",
  "The light over the back booth flickers once and steadies.",
  "The phonograph has been on the same record for an hour.",
  "A car horn from the street is muffled by the door.",
  "The icebox in the corner drips into a tin pan.",
  "A man at the bar slides a folded bill across the counter and the bartender pockets it without looking.",
  "The piano player runs his thumb along a chord but does not play.",
  "Outside, the wind picks up enough to rattle the basement grate.",
  "Someone strikes a match. The flame is taller than it should be.",
  "The radiator clangs once.",
  "The smell of cigar smoke from the back booth thickens.",
  "A glass slips a quarter-inch on the wet bar without falling.",
  "The bartender glances at the clock without reading it.",
  "Two of the bottles behind the bar are turned label-out, the rest are not.",
)

val SCRIPT_BOOTLEGGERS_WIFE = GameScript(
  total_duration_minutes = 90,
  cast = cast_bootleggers(),
  privacy_preamble = PRIVACY_PREAMBLE,
  host_cues = HostCues(
    opening_monologue = "It is nine o'clock on a Tuesday in March 1929. Twenty minutes ago they came down the alley three at a time and lifted every floorboard in the kitchen. He is at the federal building tonight. The arraignment is at midnight. The five of you knew where the floorboards were. One of you told them. You are going to figure out which one before the morning paper does.",
    success_picture = "T+30: the Wife has shown the tickets to someone. T+50: at least two players have publicly named the Singer or the Partner. T+70: the Agent is watching the Partner directly. If the table is silent at T+60 the Wife is your panic button.",
    panic_buttons = listOf(
      "Ask the Wife, out loud, whether she still trusts the Singer.",
      "Ask the Doorman whose handwriting was on the envelope.",
      "Ask the Singer to sing the song she sang Tuesday night.",
    ),
    post_game_prompts = listOf(
      "Each player: what would your character do tomorrow morning?",
      "Singer + Partner: would your characters have left together?",
      "Wife: do you forgive her?",
    ),
    recommended_cocktails = listOf("Sazerac", "Old Fashioned", "Gin Rickey"),
  ),
  beats = listOf(
    GameBeat(0, "all", "NARRATIVE",
      "The South Side, March 1929. He is in federal lockup tonight. The agents knew where to come, what to lift, and when. One of you told them.",
      host_note = "Read flat. Almost bored. The table is on edge already; you do not need to push."),
    GameBeat(3, "all", "SYSTEM",
      "Round one is poured. Take your seat. The bourbon stays on the bar."),
    GameBeat(5, "the_wife", "SNEAK",
      "While the bartender pours, cross to the coat hook by the back door. Slip both hands into his coat pockets. Take what you find. Two minutes.",
      host_note = "Pre-place a folded paper labeled 'tickets' in the coat pocket. She will discover them now."),
    GameBeat(8, "the_wife", "TWIST",
      "You find a railway ticket to St. Louis in his coat pocket, dated tomorrow. There are two.",
      actions = listOf(
        GameBeatAction("burn", "Burn it"),
        GameBeatAction("keep", "Keep it"),
        GameBeatAction("show_singer", "Show the Singer"),
      ),
    ),
    GameBeat(10, "the_partner", "TWIST",
      "You did it. Two years overdue. Survive eighty more minutes. Do not say the word \"floorboards.\"",
      actions = listOf(
        GameBeatAction("steady", "Steady"),
        GameBeatAction("plan_misdirect", "Plan a misdirect"),
      ),
      host_note = "This is the killer's only private acknowledgment of guilt. Do not surface."),
    GameBeat(12, "the_agent", "TWIST",
      "You recognize the Partner from a quiet meeting Tuesday at the diner on Halsted.",
      actions = listOf(
        GameBeatAction("press", "Press him"),
        GameBeatAction("wait", "Wait"),
        GameBeatAction("warn_partner", "Warn him"),
      ),
    ),
    GameBeat(15, "all", "CLOCK",
      "Quarter past nine. They are processing him at the federal building. The arraignment is at midnight. Two hours and forty-five minutes.",
      host_note = "Read this aloud at the table. Look at your watch. Then continue."),
    GameBeat(18, "the_singer", "TWIST",
      "A federal car was idling at the alley mouth ten minutes before the raid. You said nothing.",
      actions = listOf(
        GameBeatAction("confess", "Confess"),
        GameBeatAction("deflect", "Deflect"),
        GameBeatAction("blame_partner", "Blame Partner"),
      ),
    ),
    GameBeat(20, "the_singer", "RECON",
      "Step out the alley door for some air. While you are gone, look at whose car is parked at the corner. Five minutes.",
      host_note = "When she returns, the table will ask where she went. She lies or doesn't."),
    GameBeat(23, "the_partner", "STEP_AWAY",
      "Excuse yourself to the back kitchen — a phone call. Stay gone six minutes. Do not come back early.",
      host_note = "The empty chair is the point. Do not check on him."),
    GameBeat(26, "all", "MISSED",
      "The Partner has been gone since the phone rang. Notice his chair aloud.",
      host_note = "Read this out. Look at the empty chair when you say it."),
    GameBeat(24, "the_cook", "TWIST",
      "The Partner's lunch plate is still in the back. The phone receipt with it.",
      actions = listOf(
        GameBeatAction("hide_receipt", "Hide receipt"),
        GameBeatAction("show_wife", "Show Wife"),
        GameBeatAction("burn", "Burn it"),
      ),
      is_optional = true,
    ),
    GameBeat(28, "all", "NARRATIVE",
      "The pianist plays \"Sweet Georgia Brown.\" The bartender refills the bourbon without being asked."),
    GameBeat(30, "all", "CLOCK",
      "Half past nine. The second sweep team is on its way. If they leave this bar without a name from you, they take the lot of you in for questioning.",
      host_note = "Read in a conspiratorial whisper. Refill your own glass."),
    GameBeat(32, "the_doorman", "TWIST",
      "The envelope you took Wednesday morning was sealed with a federal stamp. You only just noticed.",
      actions = listOf(
        GameBeatAction("burn_now", "Burn it"),
        GameBeatAction("admit", "Admit it"),
        GameBeatAction("pocket", "Pocket it"),
      ),
      is_optional = true,
    ),
    GameBeat(36, "the_cousin", "TWIST",
      "The agents have your name on a list. You can see it from where you are sitting.",
      actions = listOf(
        GameBeatAction("come_clean", "Come clean"),
        GameBeatAction("blame_doorman", "Blame Doorman"),
        GameBeatAction("stall", "Stall"),
      ),
      is_optional = true,
    ),
    GameBeat(40, "the_partner", "TWIST",
      "The Agent is looking at you. He has not looked away in two minutes.",
      actions = listOf(
        GameBeatAction("toast_agent", "Toast him"),
        GameBeatAction("excuse", "Step out"),
        GameBeatAction("accuse_singer", "Accuse Singer"),
      ),
    ),
    GameBeat(42, "all", "NARRATIVE",
      "The bartender wipes the bar twice in the same spot. The pianist has stopped playing. Something the Wife found in his coat is starting to weigh on the room.",
      host_note = "Pause four seconds after \"the room.\" Let it sit. This sets up the second-ticket beat."),
    GameBeat(45, "all", "CLOCK",
      "Quarter to ten. The lawyer just arrived at the courthouse. He needs a name to take to the judge — or this becomes long-term.",
      host_note = "Hold a beat after \"long-term.\" Look at the Partner if he is at the table."),
    GameBeat(45, "the_bartender", "TWIST",
      "The Agent ordered a tall water. You can call that out from across the bar or pretend not to notice.",
      actions = listOf(
        GameBeatAction("call_out", "Call out"),
        GameBeatAction("nod_agent", "Nod to him"),
        GameBeatAction("ignore", "Ignore"),
      ),
      is_optional = true,
    ),
    GameBeat(48, "the_wife", "TWIST",
      "The second ticket is in the Singer's name. You read it again to be sure.",
      actions = listOf(
        GameBeatAction("confront_singer", "Confront her"),
        GameBeatAction("hide", "Hide it"),
        GameBeatAction("table_it", "Lay it down"),
      ),
    ),
    GameBeat(52, "the_pianist", "TWIST",
      "What you saw from the bench puts the Partner on the wrong side of Tuesday afternoon.",
      actions = listOf(
        GameBeatAction("say_aloud", "Say it"),
        GameBeatAction("tell_singer", "Tell Singer"),
        GameBeatAction("withhold", "Withhold"),
      ),
      is_optional = true,
    ),
    GameBeat(55, "all", "NARRATIVE",
      "Somewhere above, a door closes. The bartender does not look up."),
    GameBeat(60, "all", "CLOCK",
      "Ten o'clock. The agents have his ledger now. Every name in it gets a knock in the next two days unless someone speaks tonight."),
    GameBeat(62, "the_agent", "TWIST",
      "The Partner just said \"the floorboards\" without anyone mentioning them.",
      actions = listOf(
        GameBeatAction("name_him", "Name him"),
        GameBeatAction("let_it_sit", "Let it sit"),
      ),
    ),
    GameBeat(63, "the_agent", "BE_SEEN",
      "Stand. Cross to the bar slowly. Pass the Partner's chair. Hold his eye for a beat. Return without speaking.",
      host_note = "Drop the music. Let the room watch."),
    GameBeat(70, "the_partner", "TWIST",
      "You realize you slipped. Recover, deflect, or run.",
      actions = listOf(
        GameBeatAction("deflect_wife", "Accuse Wife"),
        GameBeatAction("deflect_doorman", "Accuse Doorman"),
        GameBeatAction("confess", "Confess"),
      ),
    ),
    GameBeat(75, "all", "CLOCK",
      "Quarter past ten. The arraignment is in forty-five minutes. After it begins, anything said in this room is just gossip."),
    GameBeat(78, "all", "NARRATIVE",
      "Name your suspect. A folded napkin in the center of the bar. Write the name on it. Cover it."),
    GameBeat(90, "all", "REVEAL",
      "It was the Partner.\n\nTwo years ago the bootlegger pushed him off the South Side route. He never let it go. He met the Federal Agent Tuesday at the diner on Halsted and told him about the floorboards, the schedule, and the back-room safe — dressed as a casual conversation between friends.\n\nThe Singer saw the car idling and said nothing because she had her own ticket to St. Louis in her purse. The Wife is innocent of the raid but knew about the ticket. The Doorman's envelope was unrelated — a different agent, a different case. The Federal Agent at this table covered for his informant until the Partner named the floorboards aloud and confirmed himself.\n\nIt was two years overdue.",
      killer_character_id = "the_partner",
      ending_id = "long_resentment",
      host_note = "Read the first paragraph. Pause three seconds. Read the second. Look at the Partner before you read the third."),
  ),
  cover_beat_library = BOOTLEGGER_COVERS,
)

private fun cast_bootleggers() = listOf(
  GameCharacter(
    id = "the_wife",
    name = "The Wife",
    role = "Married to the bootlegger nine years. Runs the books.",
    secret = "You discovered last week that he was planning to leave town with the Singer when the Christmas run finished.",
    objective = "Find out who took your husband down. Do not let the room learn you knew about the Singer.",
  ),
  GameCharacter(
    id = "the_partner",
    name = "The Partner",
    role = "Ran the South Side route with him until two years ago, when the bootlegger pushed him out.",
    secret = "You met with a federal agent on Tuesday. You insist it was about something else.",
    objective = "Misdirect every line of questioning. Make the Singer look like the leak.",
    bluffs = listOf(
      "I was at Maxwell's on Halsted Tuesday afternoon — the bartender there saw me at three. Whatever I did at the diner was after.",
      "The Doorman has been jumpy for a week. He took an envelope nobody can identify. That is your leak.",
      "The Singer was standing in the alley when the agents came. Ask her why she did not run.",
    ),
  ),
  GameCharacter(
    id = "the_singer",
    name = "The Singer",
    role = "Performs Tuesdays and Saturdays. In love with someone in this room.",
    secret = "You were standing outside the bar when the agents arrived. You did not raise the alarm because you wanted them to find what they found.",
    objective = "Survive the night without anyone learning you watched the agents come and let them in.",
  ),
  GameCharacter(
    id = "the_doorman",
    name = "The Doorman",
    role = "Twenty years on the South Side. Paid every Friday in cash.",
    secret = "You took an envelope from someone you did not recognize on Wednesday morning.",
    objective = "Keep your envelope private. Cooperate but reveal nothing about your own arrangements.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_agent",
    name = "The Federal Agent",
    role = "Drinks here three nights a week. Plays poker on Sundays.",
    secret = "You knew where the floorboards were because someone in this room told you, drunk, two months ago.",
    objective = "Identify your informant out loud, but only if there is no other way. Leverage is worth more than a name.",
  ),
  // ---- Optional extras. ----
  GameCharacter(
    id = "the_cousin",
    name = "The Cousin",
    role = "Family ties to the bootlegger. Drops by Tuesdays for the early shift.",
    secret = "You took a bottle off the back shelf last week without telling anyone. The agents counted it.",
    objective = "Establish you were home all of Tuesday. Recover the missing bottle's cost from the till if possible.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_cook",
    name = "The Cook",
    role = "Runs the back kitchen. Twenty-six years in basement bars.",
    secret = "You served the Partner a plate at three on Tuesday. He was on the phone the whole time.",
    objective = "Keep your kitchen out of the conversation. Do not let anyone connect Tuesday lunch to the raid.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_bartender",
    name = "The Bartender",
    role = "Pours for the South Side trade six nights a week. Hears every conversation by the bar.",
    secret = "The Federal Agent has been drinking watered drinks for two months. He has been on the clock the whole time.",
    objective = "Decide which side of the bar to be on tomorrow. Tonight, you pour and you listen.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_pianist",
    name = "The Pianist",
    role = "Plays Tuesdays and Saturdays. In love with the Singer though she does not know it yet.",
    secret = "From the bench, you saw the Partner leave the bar at half-past three Tuesday and return at four-fifteen.",
    objective = "Protect the Singer. Speak only if the room turns on her.",
    is_optional = true,
  ),
)

// ---------------------------------------------------------------------------
//  Last Toast at the Ritz — Paris, 1925. Killer: the_heiress.
// ---------------------------------------------------------------------------

private val RITZ_COVERS = listOf(
  "The chandelier above the bar trembles slightly when the elevator passes.",
  "The doorman steps in from the rue Cambon to warm his hands.",
  "A bellboy carries a stack of telegram envelopes past the bar.",
  "Frank Meier polishes a coupe glass with the cloth tucked into his apron.",
  "The smell of tuberose from the next room is thicker tonight.",
  "Two women in evening dress laugh too loud at something across the lobby.",
  "The waiter pauses at your table, then moves on without asking.",
  "A man at the far end of the bar lights a cigarette with the wrong end.",
  "The ice in the silver bucket settles.",
  "The piano player begins a Cole Porter song you have not heard in Paris before.",
  "An older couple speaking German at the corner table go silent when you pass.",
  "The brass rail along the bar has been polished to mirror brightness.",
  "A flake of paint from the ceiling lands on the marble floor without sound.",
  "The clock on the wall chimes the half-hour, three minutes late.",
  "A page boy walks past with an empty silver tray.",
  "Outside, a horse-drawn carriage clatters past, then a Citroën with a broken muffler.",
  "The bartender pours a glass of vermouth for someone who has not arrived.",
  "Through the velvet curtain into the dining room, the kitchen door swings once.",
)

private fun cast_ritz() = listOf(
  GameCharacter(
    id = "the_novelist",
    name = "The Expat Novelist",
    role = "An American writer running a tab he cannot afford to settle.",
    secret = "The dead man was the inspiration for your novel. He had read the manuscript last week.",
    objective = "Find out if anyone else read the manuscript. Settle your tab tonight by any means.",
  ),
  GameCharacter(
    id = "the_heiress",
    name = "The Heiress",
    role = "Engaged to the dead man's son.",
    secret = "He told you privately, twenty minutes before his collapse, that he would refuse his blessing.",
    objective = "Make sure no one places you near the dining room at the moment in question. Keep the fiancé's name unspoken.",
    bluffs = listOf(
      "I was at the front desk asking after a telegram from my mother in New York. The concierge can confirm.",
      "If Frank saw anyone leave that table, it was the Painter — they argued for ten full minutes.",
      "The Fixer was in the bar all night taking calls. I would have been the last person near that glass.",
    ),
  ),
  GameCharacter(
    id = "the_painter",
    name = "The Painter",
    role = "Owed the dead man a large sum from a portrait commission gone wrong.",
    secret = "You had a private conversation with the dead man at the bar an hour before he died.",
    objective = "Establish an alibi at the bar with Frank Meier. Recover the commission tonight.",
  ),
  GameCharacter(
    id = "frank_meier",
    name = "Frank Meier",
    role = "The bartender. Forty years behind the Ritz bar.",
    secret = "You saw the Heiress disappear into the dining room for three minutes during which the glass sat unattended.",
    objective = "Identify the killer in your bar before the morning papers arrive. Your reputation depends on it.",
  ),
  GameCharacter(
    id = "the_fixer",
    name = "The Fixer",
    role = "A man who solves problems for wealthy Americans abroad.",
    secret = "You were paid in advance to deliver a message tonight. You did not have time to deliver it.",
    objective = "Recover the message envelope from the dead man's coat before another guest reads it.",
    is_optional = true,
  ),
  // ---- Optional extras. ----
  GameCharacter(
    id = "the_couturiere",
    name = "The Couturière",
    role = "The Heiress's dressmaker. Was at the bar tonight to fit the train of the evening gown.",
    secret = "You watched the Heiress slip something from her compact into the champagne glass when no one else looked.",
    objective = "Decide whether the Heiress's account is worth the secret. Do not lose the commission either way.",
  ),
  GameCharacter(
    id = "the_concierge",
    name = "The Concierge",
    role = "Front-of-house at the Ritz. Sees every guest, remembers every name.",
    secret = "The dead man asked you yesterday whether the Fixer was registered at the hotel. You said yes.",
    objective = "Protect the Ritz from a public mess. Steer the table away from the front desk.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_cigarette_girl",
    name = "The Cigarette Girl",
    role = "Works the bar with the silver tray on a strap. Knew the dead man by sight.",
    secret = "He bought one cigarette from you tonight and asked you to deliver a note to the Heiress.",
    objective = "Decide whether to mention the note. The Ritz pays you weekly. The Heiress could pay you better.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_senator",
    name = "The American Senator",
    role = "On holiday in Paris with his wife. Sat two seats from the bar tonight.",
    secret = "You hired the Fixer last week and your message has not been delivered yet.",
    objective = "Recover the message from the Fixer before it leaves this bar tonight.",
    is_optional = true,
  ),
)

val SCRIPT_LAST_TOAST_RITZ = GameScript(
  total_duration_minutes = 90,
  cast = cast_ritz(),
  cover_beat_library = RITZ_COVERS,
  privacy_preamble = PRIVACY_PREAMBLE,
  host_cues = HostCues(
    opening_monologue = "It is autumn, 1925, at the Ritz in Paris. An hour ago a wealthy American gentleman finished his champagne, stood, and did not reach the door. Frank Meier — who has poured at this bar for forty years — has a theory but wants yours first. The four of you, and any of the staff who saw what happened, are going to sit at this bar and reconstruct the last cocktail of his life. Before sunrise. Before the morning papers in three countries decide who he was.",
    success_picture = "T+30: the compact has come up in conversation. T+50: Frank has either named the Heiress or made the room name her. T+70: the Heiress has either confessed or accused someone else. If at T+50 Frank has not surfaced what he knows, fire panic button #2.",
    panic_buttons = listOf(
      "Walk to the bar. Refill the Heiress's coupe slowly. Set the bottle down between her and the Painter.",
      "Ask Frank, out loud, whether he has ever seen a guest leave the bar in the middle of a conversation and come back without being asked.",
      "Ask the Couturière to stand and re-pin a sash on the Heiress's dress.",
    ),
    post_game_prompts = listOf(
      "Heiress: did the fiancé know?",
      "Frank: when did you decide to let the table answer?",
      "Each player: read aloud your character's last drink order tonight.",
    ),
    recommended_cocktails = listOf("French 75", "Sidecar", "Champagne Cocktail"),
  ),
  beats = listOf(
    GameBeat(0, "all", "NARRATIVE",
      "The Ritz bar, Paris, autumn 1925. He finished the champagne. He stood. He did not reach the door. Frank Meier has a theory and wants yours first.",
      host_note = "Read in a conspiratorial whisper. Polish a glass while you read."),
    GameBeat(3, "all", "SYSTEM",
      "Take the seat your character took an hour ago. The coupes are full. Frank is listening."),
    GameBeat(5, "the_heiress", "TWIST",
      "You did it. Three minutes in the dining room, a vial in your glove, a son cut off. Survive eighty more minutes. Do not look at Frank.",
      actions = listOf(
        GameBeatAction("steady", "Steady"),
        GameBeatAction("plan_bluff", "Plan a bluff"),
      ),
      host_note = "Killer-first private acknowledgment. Do not surface."),
    GameBeat(9, "the_painter", "TWIST",
      "Frank refills your glass and murmurs, \"I saw your conversation with him at the bar. So did the boy.\"",
      actions = listOf(
        GameBeatAction("pay_frank", "Pay Frank"),
        GameBeatAction("dismiss", "Dismiss"),
        GameBeatAction("admit", "Admit it"),
      ),
    ),
    GameBeat(13, "the_heiress", "TWIST",
      "Frank's eyes settle on you for one second too long.",
      actions = listOf(
        GameBeatAction("smile", "Smile back"),
        GameBeatAction("look_away", "Look away"),
        GameBeatAction("speak_first", "Speak first"),
      ),
    ),
    GameBeat(14, "the_heiress", "STEP_AWAY",
      "Excuse yourself to the dining room. Three minutes. Walk past the empty table where he was sitting. Return slowly.",
      host_note = "She is recreating the window. Frank watches every step."),
    GameBeat(14, "frank_meier", "BE_SEEN",
      "When the Heiress stands, set down your towel. Watch her walk across the floor. Do not look away until she returns.",
      host_note = "Paired with her STEP_AWAY. The table sees you watch her."),
    GameBeat(15, "all", "CLOCK",
      "Half past ten. The morning editions go to bed at three. You have four and a half hours to decide what story Paris reads about the Ritz tomorrow.",
      host_note = "Hold a beat. Look at Frank."),
    GameBeat(20, "the_fixer", "TWIST",
      "The envelope is still in the dead man's coat, hanging by the door.",
      actions = listOf(
        GameBeatAction("retrieve", "Retrieve it"),
        GameBeatAction("send_boy", "Send a boy"),
        GameBeatAction("wait", "Wait"),
      ),
      is_optional = true,
    ),
    GameBeat(26, "the_novelist", "TWIST",
      "Across the bar, a stranger is reading what looks very much like your manuscript.",
      actions = listOf(
        GameBeatAction("approach", "Approach"),
        GameBeatAction("watch", "Watch"),
        GameBeatAction("ask_frank", "Ask Frank"),
      ),
    ),
    GameBeat(30, "the_couturiere", "GATHER_INTEL",
      "Excuse yourself to the powder room. The Heiress's compact is on the marble counter. The mirror is mirrored. Three minutes. Retrieve it.",
      host_note = "Pre-place a small powder compact on the counter. She returns with physical evidence."),
    GameBeat(31, "the_couturiere", "TWIST",
      "What you saw in the compact is worth a year of the Heiress's commissions, or nothing.",
      actions = listOf(
        GameBeatAction("tell_frank", "Tell Frank"),
        GameBeatAction("approach_heiress", "Approach her"),
        GameBeatAction("withhold", "Withhold"),
      ),
    ),
    GameBeat(30, "all", "CLOCK",
      "Eleven o'clock. The body is still in the dining room. The night porter is asking the manager what to do."),
    GameBeat(33, "all", "NARRATIVE",
      "Frank Meier polishes a coupe and waits.",
      host_note = "Hand a polishing cloth to whichever guest is closest to the bar."),
    GameBeat(38, "frank_meier", "TWIST",
      "You know what you saw. You also know that knowing is not the same as proving. Choose.",
      actions = listOf(
        GameBeatAction("hint", "Hint at it"),
        GameBeatAction("approach_heiress", "Approach her"),
        GameBeatAction("withhold", "Withhold"),
      ),
      host_note = "Frank knows but does not name. Audit recommendation — keep him as host-proxy, not solver."),
    GameBeat(42, "the_cigarette_girl", "DEAD_DROP",
      "Slip the folded note onto the lacquer tray at the end of the bar. Walk away. Do not point.",
      host_note = "Pre-place the tray. Any guest may find the note now.",
      is_optional = true,
    ),
    GameBeat(42, "the_cigarette_girl", "TWIST",
      "The folded note he asked you to deliver is still in your apron pocket.",
      actions = listOf(
        GameBeatAction("deliver", "Deliver it"),
        GameBeatAction("read_aloud", "Read aloud"),
        GameBeatAction("burn", "Burn it"),
      ),
      is_optional = true,
    ),
    GameBeat(45, "all", "CLOCK",
      "Quarter past eleven. The fiancé — the dead man's son — is now in the lobby asking for the Heiress by name."),
    GameBeat(46, "the_heiress", "TWIST",
      "Your fiancé sent a telegram tonight. It is at the front desk. It mentions you.",
      actions = listOf(
        GameBeatAction("retrieve_now", "Retrieve it"),
        GameBeatAction("ignore", "Ignore"),
        GameBeatAction("ask_fixer", "Ask the Fixer"),
      ),
    ),
    GameBeat(48, "the_senator", "TWIST",
      "The Fixer has not looked at you once tonight. You paid for that message in cash a week ago.",
      actions = listOf(
        GameBeatAction("press_fixer", "Press Fixer"),
        GameBeatAction("ask_frank", "Ask Frank"),
        GameBeatAction("wait", "Wait"),
      ),
      is_optional = true,
    ),
    GameBeat(50, "the_concierge", "RENDEZVOUS",
      "Meet the Fixer at the front desk for two minutes. Decide what you tell each other about the booking under a different name.",
      host_note = "Paired beat — fires to the Fixer too.",
      is_optional = true,
    ),
    GameBeat(50, "the_fixer", "RENDEZVOUS",
      "Meet the Concierge at the front desk for two minutes. Decide what you tell each other about the booking under a different name.",
      is_optional = true,
    ),
    GameBeat(50, "the_concierge", "TWIST",
      "The Fixer's room is booked under a different name than the one at this table.",
      actions = listOf(
        GameBeatAction("name_aloud", "Say aloud"),
        GameBeatAction("warn_fixer", "Warn him"),
        GameBeatAction("hold_it", "Hold it"),
      ),
      is_optional = true,
    ),
    GameBeat(54, "all", "NARRATIVE",
      "The piano changes songs. The lobby clock chimes the half-hour."),
    GameBeat(60, "all", "CLOCK",
      "Midnight. The morning paper goes to print in three hours. The Ritz's manager wants a name in two."),
    GameBeat(60, "the_painter", "TWIST",
      "The argument you had with him at the bar is the only window anyone could have used the table. Without realizing it, you may have given the killer the window.",
      actions = listOf(
        GameBeatAction("admit_window", "Admit it"),
        GameBeatAction("blame_heiress", "Blame Heiress"),
        GameBeatAction("blame_fixer", "Blame Fixer"),
      ),
    ),
    GameBeat(68, "the_heiress", "TWIST",
      "The room is closing on you. Three minutes in the dining room is a long time.",
      actions = listOf(
        GameBeatAction("deflect_novelist", "Accuse Novelist"),
        GameBeatAction("deflect_painter", "Accuse Painter"),
        GameBeatAction("stay_silent", "Stay silent"),
      ),
    ),
    GameBeat(75, "all", "CLOCK",
      "Quarter past midnight. Last call. The night porter is at the door of this bar."),
    GameBeat(76, "all", "NARRATIVE",
      "Frank sets one last coupe on the bar. The room makes its decision."),
    GameBeat(80, "all", "NARRATIVE",
      "Name your suspect on the back of the bar receipt and pass it to Frank."),
    GameBeat(90, "all", "REVEAL",
      "It was the Heiress.\n\nThe fiancé — the dead man's son — was about to be cut off. He had told her the day before that his father would refuse his blessing. She arrived at the Ritz with a small vial of digitalis in a powder compact. When the Painter pulled the dead man into an argument at the bar, she stepped into the dining room for three minutes. Frank Meier saw the glass sit. She returned, took the seat opposite him, and waited.\n\nThe Novelist's manuscript was unrelated — a stranger at the bar was reading a different book. The Fixer's message was unrelated — a real estate matter for an American senator. The Painter's debt was real but did not move the dose.\n\nFrank Meier knew before the second cocktail. He let the table arrive on its own.",
      killer_character_id = "the_heiress",
      ending_id = "patient_poison",
    ),
  ),
)

// ---------------------------------------------------------------------------
//  Heir to the Pendennis — Louisville, 1923. Killer: youngest_son.
// ---------------------------------------------------------------------------

private val PENDENNIS_COVERS = listOf(
  "The grandfather clock in the front hall ticks a half-beat slower than your watch.",
  "The Colonel's old hound shifts on the rug by the fire.",
  "A log in the hearth settles into the coals.",
  "The smell of bourbon from the sideboard is stronger than the smell of the food.",
  "Outside, a horse whinnies in the stable. Then quiet.",
  "The mantel clock chimes a single hollow note.",
  "Two of the candles on the table burn down at the same rate. The third does not.",
  "A page from a newspaper rustles on the side table though no window is open.",
  "The Housekeeper passes the doorway carrying a folded cloth and does not look in.",
  "The chandelier creaks once on its chain.",
  "The smell of cigar smoke seeps in from the library across the hall.",
  "Somewhere in the house, a door is closed very gently.",
  "A floorboard in the hallway above gives once and goes still.",
  "The decanter on the sideboard catches the lamp light.",
  "An ash falls from the cigar in the ashtray onto the linen.",
  "From the front porch, the night insects pick up volume and drop off again.",
  "The portrait of the Colonel over the mantel watches the table without blinking.",
  "Down the hall, the longcase clock in the library is exactly half a minute fast.",
)

private fun cast_pendennis() = listOf(
  GameCharacter(
    id = "eldest_son",
    name = "The Eldest Son",
    role = "Gambler. Owes the Colonel a sum the family has been quiet about.",
    secret = "You overheard the Colonel telling the Family Lawyer that the new draft cut you entirely.",
    objective = "Keep the new draft from being signed. Settle your debt before any audit.",
  ),
  GameCharacter(
    id = "the_daughter",
    name = "The Daughter",
    role = "Frozen out of the will by Southern custom.",
    secret = "The Colonel had sent you a private telegram yesterday saying he was restoring your share.",
    objective = "Get the telegram on the record before the night ends. Restoration must be witnessed.",
    is_optional = true,
  ),
  GameCharacter(
    id = "youngest_son",
    name = "The Youngest Son",
    role = "Returned from Paris last week, suspiciously well-dressed.",
    secret = "You had been writing checks against an account that did not exist, signed in the Colonel's name.",
    objective = "Make the Eldest Son look guilty. Bury the checks. Avoid any mention of Paris.",
    bluffs = listOf(
      "I was in the front parlor with the Daughter from five until six — ask her, she had the telegram open on the side table.",
      "The Eldest owed him a sum that would close a small bank. Look at his hands tonight.",
      "Paris was three months. Whatever the bank wrote to him was somebody else signing my name.",
    ),
  ),
  GameCharacter(
    id = "family_lawyer",
    name = "The Family Lawyer",
    role = "Drafted the new will today.",
    secret = "You suggested the cuts to the Eldest and Youngest Son.",
    objective = "Leave the house tonight without anyone learning the cuts were your idea.",
  ),
  GameCharacter(
    id = "the_housekeeper",
    name = "The Housekeeper",
    role = "Forty-one years in the Colonel's household.",
    secret = "You saw the Youngest Son go into the study at five forty-five and emerge at six.",
    objective = "Decide whether to mention what you saw. The family has been good to you for forty-one years.",
  ),
  GameCharacter(
    id = "stable_master",
    name = "The Stable Master",
    role = "Came in for tonight's dinner from the racing stable.",
    secret = "The Colonel had told you at three o'clock that you would inherit a small share of the stable.",
    objective = "Confirm your share is in writing. Stay out of the family knife fight.",
    is_optional = true,
  ),
  // ---- Optional extra. ----
  GameCharacter(
    id = "the_visiting_cousin",
    name = "The Visiting Cousin",
    role = "A second cousin from St. Louis, in town for the Derby.",
    secret = "The Colonel had written you into the old draft for a small share of the bourbon stocks. The new draft removes you.",
    objective = "Find out if the new draft has been signed. Make the case for the old draft over dessert.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_butler",
    name = "The Butler",
    role = "Forty-three years with the Colonel. Older than the Housekeeper. Speaks less.",
    secret = "You let the Family Lawyer into the study at four-thirty for ten minutes. He left with a folder.",
    objective = "Decide whether to confirm the Housekeeper's account. You have served this house longer than she has.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_doctor",
    name = "The Family Doctor",
    role = "Treated the Colonel for thirty years. Came for tonight's dinner.",
    secret = "The Colonel asked you last week, in passing, whether the Youngest Son had been buying anything peculiar from pharmacies in Paris. You said you didn't know.",
    objective = "Steer the table away from the question of method. The family does not need a coroner's column.",
    is_optional = true,
  ),
)

val SCRIPT_HEIR_PENDENNIS = GameScript(
  total_duration_minutes = 90,
  cast = cast_pendennis(),
  cover_beat_library = PENDENNIS_COVERS,
  privacy_preamble = PRIVACY_PREAMBLE,
  host_cues = HostCues(
    opening_monologue = "It is Derby Eve, 1923, in Louisville. The Colonel was found in his study at quarter past six this evening. The new draft of his will is on his desk, unsigned. The old draft remains in force until the lawyer signs the new one tonight or breakfast tomorrow. The six of you, plus the staff, were the only souls in this house this afternoon. The reading is at nine in the morning. Before then, you are going to decide what story this family takes to the track.",
    success_picture = "T+30: at least one player has named the Youngest Son aloud or hinted at his Paris trip. T+50: the Housekeeper has begun to circle her testimony. T+70: the new draft has been produced — burned, pocketed, or set on the table. If the Housekeeper is still silent at T+50, fire panic button #1.",
    panic_buttons = listOf(
      "Walk into the kitchen. Ask the Housekeeper, where you can be heard by the table, whether the bourbon needs refreshing.",
      "Lift the Family Lawyer's coat from the chair. Hand it to him with both hands, slowly.",
      "Ask the Doctor whether the Colonel had been complaining of his heart in the last week.",
    ),
    post_game_prompts = listOf(
      "Housekeeper: was forty-one years long enough?",
      "Youngest Son: when did you decide?",
      "Each player: who do you stay with after tomorrow's reading?",
    ),
    recommended_cocktails = listOf("Mint Julep", "Old Fashioned", "Whiskey Sour"),
  ),
  beats = listOf(
    GameBeat(0, "all", "NARRATIVE",
      "Louisville, Derby Eve, 1923. The Colonel is dead in his study. The new draft of his will sits unsigned on the desk.",
      host_note = "Read low. The room is in mourning even if the family is not."),
    GameBeat(3, "all", "SYSTEM",
      "Take your seat at the long table. The bourbon is poured. The Housekeeper waits in the kitchen."),
    GameBeat(5, "youngest_son", "TWIST",
      "You did it. The Colonel called you in at five-thirty about the checks. He was alive when you closed the door. He was not when you left. Survive eighty more minutes. Do not mention Paris.",
      actions = listOf(
        GameBeatAction("steady", "Steady"),
        GameBeatAction("plan_bluff", "Plan a bluff"),
      ),
      host_note = "Killer-first private acknowledgment. Do not surface."),
    GameBeat(8, "eldest_son", "SNEAK",
      "While the Housekeeper is in the kitchen, slip across the room. The Lawyer's coat is on the chair. The new draft is folded in the inside pocket. Two minutes. Read it where no one will see.",
      host_note = "Pre-place a folded paper labeled 'WILL · DRAFT II' inside the lawyer's coat. He retrieves it now."),
    GameBeat(9, "eldest_son", "TWIST",
      "The new draft cuts you to a single dollar. The Lawyer's coat is across the room.",
      actions = listOf(
        GameBeatAction("take", "Take it"),
        GameBeatAction("read", "Read it"),
        GameBeatAction("leave", "Leave it"),
      ),
    ),
    GameBeat(13, "the_daughter", "GATHER_INTEL",
      "Excuse yourself upstairs to your room for three minutes. The telegram is in the drawer of your dressing table. Bring it down folded.",
      host_note = "Pre-place a folded telegram in the upstairs room.",
      is_optional = true,
    ),
    GameBeat(13, "the_daughter", "TWIST",
      "The telegram is in your reticule. Read it tonight or it does not count.",
      actions = listOf(
        GameBeatAction("read_aloud", "Read aloud"),
        GameBeatAction("show_lawyer", "Show Lawyer"),
        GameBeatAction("hold", "Hold it"),
      ),
      is_optional = true,
    ),
    GameBeat(15, "all", "CLOCK",
      "Quarter past seven. The reading is at nine tomorrow morning. The Lawyer needs the new draft signed before midnight or the old draft stands.",
      host_note = "Hold a beat after \"old draft stands.\" Look at the Eldest."),
    GameBeat(20, "youngest_son", "STEP_AWAY",
      "Excuse yourself to the study for five minutes. Stand where you stood at five-thirty. Do not touch the desk.",
      host_note = "He is recreating the original window. The Housekeeper watches him go."),
    GameBeat(20, "the_housekeeper", "BE_SEEN",
      "When the Youngest stands, set down the polishing cloth. Stand in the kitchen doorway. Watch him cross to the study. Do not look away.",
      host_note = "Paired beat. The table sees the Housekeeper watch."),
    GameBeat(26, "stable_master", "TWIST",
      "The stable share was a verbal promise. There is no paper.",
      actions = listOf(
        GameBeatAction("ask_lawyer", "Ask Lawyer"),
        GameBeatAction("ask_daughter", "Ask Daughter"),
        GameBeatAction("wait", "Wait"),
      ),
      is_optional = true,
    ),
    GameBeat(30, "all", "CLOCK",
      "Half past seven. The Colonel has been on the study floor for two hours. The Housekeeper has not been into that room since the bell rang."),
    GameBeat(30, "the_visiting_cousin", "TWIST",
      "The Housekeeper sets a glass of bourbon by your elbow that you did not ask for.",
      actions = listOf(
        GameBeatAction("thank", "Thank her"),
        GameBeatAction("ask_old_draft", "Ask about old draft"),
        GameBeatAction("watch", "Watch her"),
      ),
      is_optional = true,
    ),
    GameBeat(33, "all", "NARRATIVE",
      "The clock in the hall chimes the half-hour. The hound shifts by the fire."),
    GameBeat(38, "family_lawyer", "TWIST",
      "The Daughter has the telegram. If she reads it aloud, the cuts are your work alone.",
      actions = listOf(
        GameBeatAction("preempt", "Speak first"),
        GameBeatAction("deny", "Deny it"),
        GameBeatAction("blame_youngest", "Blame Youngest"),
      ),
    ),
    GameBeat(42, "the_butler", "RENDEZVOUS",
      "Excuse yourself to the library. The Family Lawyer will meet you there for two minutes. Decide what you both say about the folder.",
      host_note = "Paired beat. The library is across the hall — two empty seats at once.",
      is_optional = true,
    ),
    GameBeat(42, "family_lawyer", "RENDEZVOUS",
      "Excuse yourself to the library. The Butler is waiting. Two minutes. Decide what you both say about the folder.",
    ),
    GameBeat(42, "the_butler", "TWIST",
      "What you saw at four-thirty puts the Lawyer in the study with a folder before the Youngest went in.",
      actions = listOf(
        GameBeatAction("name_lawyer", "Name Lawyer"),
        GameBeatAction("hint", "Hint at it"),
        GameBeatAction("withhold", "Withhold"),
      ),
      is_optional = true,
    ),
    GameBeat(45, "all", "CLOCK",
      "Quarter to eight. The undertaker is at the back porch. The Lawyer is running out of room to redraft."),
    GameBeat(46, "the_housekeeper", "TWIST",
      "You have served this family forty-one years. Tonight is the night to speak or never speak again.",
      actions = listOf(
        GameBeatAction("speak_youngest", "Name Youngest"),
        GameBeatAction("hint", "Hint at it"),
        GameBeatAction("withhold", "Withhold"),
      ),
      host_note = "If she chooses Hint or Withhold, fire panic button #1 at T+52."),
    GameBeat(50, "the_doctor", "TWIST",
      "The Colonel asked you about Paris pharmacies last week. The Youngest was in Paris three months. Connect or do not.",
      actions = listOf(
        GameBeatAction("name_paris", "Name Paris"),
        GameBeatAction("deflect", "Deflect"),
        GameBeatAction("call_heart", "Call it heart"),
      ),
      is_optional = true,
    ),
    GameBeat(54, "all", "NARRATIVE",
      "The decanter is empty. The Housekeeper does not bring another."),
    GameBeat(60, "all", "CLOCK",
      "Eight o'clock. The Lawyer is at the writing desk. The pen is in his hand."),
    GameBeat(60, "youngest_son", "TWIST",
      "The Housekeeper is going to say it. You have one move left.",
      actions = listOf(
        GameBeatAction("blame_eldest_loud", "Accuse Eldest"),
        GameBeatAction("blame_lawyer", "Accuse Lawyer"),
        GameBeatAction("confess", "Confess"),
      ),
    ),
    GameBeat(68, "eldest_son", "TWIST",
      "The new draft cuts you to a single dollar. Burn it before it is signed.",
      actions = listOf(
        GameBeatAction("burn", "Burn it"),
        GameBeatAction("pocket", "Pocket it"),
        GameBeatAction("present", "Present it"),
      ),
      host_note = "If he burns it, the old draft stands at the reading. The table should know."),
    GameBeat(75, "all", "CLOCK",
      "Quarter past eight. Forty-five minutes until the reading is no longer your private matter."),
    GameBeat(76, "all", "NARRATIVE",
      "The Housekeeper stands at the doorway with the cloth still folded over her arm."),
    GameBeat(80, "all", "NARRATIVE",
      "Name your suspect. Write it on the back of a calling card and place it under the centerpiece.",
      host_note = "Hand out calling cards before you read this."),
    GameBeat(90, "all", "REVEAL",
      "The Youngest Son did it.\n\nHe had been writing checks against an account that did not exist, signed in the Colonel's name. The bank notified the Colonel last week. The Colonel called him into the study at five-thirty to confront him. The Youngest carried a small vial of digitalis tincture from a Paris pharmacy, slipped it into the bourbon glass on the side table, and waited until the Colonel drank. He was on the floor by six. The Housekeeper saw the Youngest emerge from the study at six — the only window in which the Colonel was alive and alone.\n\nThe new draft was the Lawyer's idea and it cut both sons. The Daughter's telegram was real — restoration in her favor. The Eldest's debt was old news. The Stable Master's share was always going to be honored. The Butler saw the Lawyer with the folder at four-thirty; that was the unsigned new draft, not a murder weapon. The Doctor's pharmacy question was the thread. The Housekeeper waited because forty-one years asks for patience.\n\nThe Youngest could not allow the audit.",
      killer_character_id = "youngest_son",
      ending_id = "audit_avoidance",
      host_note = "Pause four seconds at \"He was on the floor by six.\" Look at the Youngest at \"audit.\""),
  ),
)

// ---------------------------------------------------------------------------
//  The Vanishing Socialite — West Egg, 1926. Killer (engineered): the_host.
// ---------------------------------------------------------------------------

private val WEST_EGG_COVERS = listOf(
  "From the lawn, a saxophone holds a note longer than the trumpet expects.",
  "Beyond the windows, the green light at the end of the dock blinks once.",
  "A waiter passes carrying a tray of pink coupes.",
  "The breeze through the open french doors stirs the curtain.",
  "Out on the gravel drive, a car door closes.",
  "The pearl strand around someone's neck catches the chandelier light.",
  "A young couple at the next sofa stop talking when you look over.",
  "An ice sculpture by the buffet has lost the tip of one wing.",
  "The band finishes a fox-trot and pauses before the next number.",
  "A cigarette girl with a tray on a strap walks past without stopping.",
  "From the second floor, a window is opened and closed again.",
  "The smell of gin from the bar carries across the room.",
  "A telephone rings somewhere in the house and is answered after one ring.",
  "The piano player at the corner stops playing to drink and starts again.",
  "Through the french doors, a couple on the lawn are speaking too quietly to hear.",
  "Out on the Sound, a small boat shows a single yellow light, then goes dark.",
  "Someone at the bar laughs in a way that does not sound like a laugh.",
  "An older woman pulls her shawl tighter though the room is warm.",
)

private fun cast_west_egg() = listOf(
  GameCharacter(
    id = "the_host",
    name = "The Host",
    role = "A West Egg newcomer. Was once in love with the vanished socialite.",
    secret = "She had agreed to leave with you tonight before the party. She did not show up to the agreed meeting point.",
    objective = "Buy three more hours. Keep the room from calling the police until dawn.",
    bluffs = listOf(
      "I was on the back terrace from eleven thirty to twelve. The Bandleader saw me. The Doctor saw me.",
      "If anyone saw a figure on the lawn at eleven forty, look at the Aviator — he was the only other man at this party with pale hair.",
      "The Husband has been asking me about sedatives for a week. Ask the Doctor.",
    ),
  ),
  GameCharacter(
    id = "the_husband",
    name = "The Husband",
    role = "Married to the vanished socialite.",
    secret = "You were on the lawn from eleven thirty to midnight. You saw your wife with a figure whose hair caught the lamp light. Your eyes are not what they were.",
    objective = "Identify who she was with on the lawn. Establish that she was alive at midnight.",
  ),
  GameCharacter(
    id = "the_bootlegger",
    name = "The Bootlegger",
    role = "Delivered the champagne.",
    secret = "You saw the vanished socialite speak with the Husband at eleven forty. You saw her walk away alive.",
    objective = "Keep your name off any record kept tonight. You saw something but you were never here.",
  ),
  GameCharacter(
    id = "the_journalist",
    name = "The Journalist",
    role = "Was at the party to write a profile of the Host.",
    secret = "Your notebook contains a draft of a story that implicates the Host in something the Husband does not yet know.",
    objective = "Get the story. The notebook in your bag is worth more than anyone at this table.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_sister",
    name = "The Sister",
    role = "The vanished socialite's sister. Came late. Was sober.",
    secret = "Your sister had been planning to disappear tonight. She left a note in the powder room before midnight.",
    objective = "Protect your sister's escape. Misdirect for three more hours and she is free.",
  ),
  // ---- Optional extras. ----
  GameCharacter(
    id = "the_driver",
    name = "The Driver",
    role = "Drove the Husband from Manhattan tonight. Sat with the car at the back of the property after dropping off.",
    secret = "A young woman matching the socialite's description got into a different car at the back gate at twelve oh five.",
    objective = "Decide which of your two employers — the Husband or the Host — you want to keep next week.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_maid",
    name = "The Maid",
    role = "On loan from the Plaza for tonight's party. Worked the powder room.",
    secret = "You saw the socialite write a note at eleven forty and fold it into the mirror's edge.",
    objective = "Keep the Plaza's name out of any record kept tonight. Tips depend on it.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_bandleader",
    name = "The Bandleader",
    role = "Brought eleven musicians from a Harlem dance hall for tonight. Plays until the last guest leaves.",
    secret = "From the bandstand, you saw the socialite walk past the band at eleven fifty-five, alone, headed to the back.",
    objective = "Play through. Speak to the Host first if a name needs to come up — your wage tonight goes through him.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_doctor",
    name = "The Party Doctor",
    role = "A Manhattan physician invited for the company. Two cocktails in.",
    secret = "The Husband asked you privately last week about sedatives that pass through a person quickly.",
    objective = "Stay sober enough to remember what the Husband asked you. Decide whether to mention it.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_aviator",
    name = "The Aviator",
    role = "Stage-show pilot. Came with the band's car. Knows the back roads of Long Island.",
    secret = "You agreed last week to fly someone out of an airfield in Glen Cove tonight at one in the morning.",
    objective = "Keep your appointment without naming the passenger. The fee is half up front.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_cigarette_girl",
    name = "The Cigarette Girl",
    role = "Works parties on the North Shore. Knows half the guests by sight.",
    secret = "The socialite asked you for matches at eleven fifty. Her hand was steady.",
    objective = "Sell every pack on the tray before two in the morning. Do not get involved.",
    is_optional = true,
  ),
  GameCharacter(
    id = "the_photographer",
    name = "The Society Photographer",
    role = "Hired by the Journalist's paper to shoot tonight's profile.",
    secret = "One of your plates shows the Host and the socialite speaking on the back terrace at half-past eleven.",
    objective = "Decide whether the plate is worth selling to the paper or selling to the Host.",
    is_optional = true,
  ),
)

val SCRIPT_VANISHING_SOCIALITE = GameScript(
  total_duration_minutes = 90,
  cast = cast_west_egg(),
  cover_beat_library = WEST_EGG_COVERS,
  privacy_preamble = PRIVACY_PREAMBLE,
  solution_type = "DISAPPEARANCE",
  host_cues = HostCues(
    opening_monologue = "It is summer, 1926, West Egg, Long Island. At midnight a young socialite walked out of the ballroom of this house with a Pink Lady in her hand. She did not reach her car. The Host has gathered the people who saw her last in the library, with the door closed. The band is still playing outside. Before dawn, the four of you are going to decide whether this is a body, a kidnapping, or something else entirely. Whatever you decide will be in the morning papers by ten.",
    success_picture = "T+30: at least one player has said \"she left on her own.\" T+60: the genre has flipped in the room — it is no longer a body case. T+80: the Host is either named or has walked away with three hours. If the room still thinks this is a murder at T+50, fire panic button #2.",
    panic_buttons = listOf(
      "Walk to the french doors. Open them. Stand a moment. Listen to the band. Close them again without speaking.",
      "Ask the Husband, where the Host can hear, whether his eyes have been examined this year.",
      "Refill the Sister's glass. Set the bottle in front of her, not the tray.",
    ),
    post_game_prompts = listOf(
      "Sister: where is she now?",
      "Husband: what would you have done with three more hours?",
      "Host: was it worth West Egg?",
    ),
    recommended_cocktails = listOf("Pink Lady", "French 75", "Bee's Knees"),
  ),
  beats = listOf(
    GameBeat(0, "all", "NARRATIVE",
      "West Egg, summer 1926. She left the ballroom at midnight with a Pink Lady in her hand. She did not reach her car. The Host has gathered you in the library.",
      host_note = "Read with the band audible. Do not close the french doors until T+76."),
    GameBeat(3, "all", "SYSTEM",
      "Take a seat in the library. The champagne is on the sideboard. The band is still playing outside."),
    GameBeat(5, "the_host", "TWIST",
      "You did it — not the killing, the engineering. She agreed to leave with you and did not appear at the meeting point. You panicked and stayed. Survive ninety minutes without naming the airfield.",
      actions = listOf(
        GameBeatAction("steady", "Steady"),
        GameBeatAction("plan_bluff", "Plan a bluff"),
      ),
      host_note = "Killer-first private acknowledgment. The 'killer' is the architect, not a murderer. Do not surface."),
    GameBeat(8, "the_sister", "STEP_AWAY",
      "Excuse yourself to the powder room. Three minutes. Retrieve the note from the mirror's edge. Burn it in the candle on the way back, or hide it deeper.",
      host_note = "Pre-place a folded note tucked into the edge of the powder-room mirror.",
    ),
    GameBeat(8, "the_sister", "TWIST",
      "The note from the powder room is folded inside your glove. Burn it or hide it deeper.",
      actions = listOf(
        GameBeatAction("burn", "Burn it"),
        GameBeatAction("hide", "Hide deeper"),
        GameBeatAction("read", "Re-read"),
      ),
    ),
    GameBeat(13, "the_husband", "STEP_AWAY",
      "Excuse yourself to the lawn for four minutes. Stand where you stood at eleven thirty. Look at the library windows. Return slowly.",
      host_note = "He is recreating his own alibi window. The table sees his chair empty."),
    GameBeat(13, "the_husband", "TWIST",
      "On the lawn, the figure she was speaking with had pale hair. The Host has pale hair. The Aviator has pale hair. Your eyes are not what they were.",
      actions = listOf(
        GameBeatAction("name_host", "Name Host"),
        GameBeatAction("name_aviator", "Name Aviator"),
        GameBeatAction("watch_both", "Watch both"),
      ),
    ),
    GameBeat(15, "all", "CLOCK",
      "Quarter past midnight. The valet has not returned. The morning papers go to press at three. You have two and three quarters hours to decide what story West Egg wakes up to.",
      host_note = "Hold a beat. Look at the Host."),
    GameBeat(20, "the_journalist", "TWIST",
      "The notebook in your bag has a draft headline: \"The Host's Wife in West Egg, 1922.\"",
      actions = listOf(
        GameBeatAction("show_husband", "Show Husband"),
        GameBeatAction("offer_host", "Offer Host"),
        GameBeatAction("hold", "Hold it"),
      ),
      is_optional = true,
    ),
    GameBeat(22, "the_bandleader", "BE_SEEN",
      "From the bandstand outside, walk slowly past the library french doors. Look in. Keep playing in your head. Walk past again two minutes later.",
      host_note = "Drop the music to a low number while he passes both times.",
      is_optional = true,
    ),
    GameBeat(22, "the_bandleader", "TWIST",
      "From the stand you saw her walk past at eleven fifty-five toward the back of the property.",
      actions = listOf(
        GameBeatAction("tell_host", "Tell Host"),
        GameBeatAction("tell_husband", "Tell Husband"),
        GameBeatAction("play_on", "Play on"),
      ),
      is_optional = true,
    ),
    GameBeat(26, "the_bootlegger", "TWIST",
      "The valet is asking which car you came in. He has not asked anyone else.",
      actions = listOf(
        GameBeatAction("leave", "Leave now"),
        GameBeatAction("bluff", "Bluff"),
        GameBeatAction("pay_valet", "Pay valet"),
      ),
    ),
    GameBeat(28, "the_cigarette_girl", "TWIST",
      "She asked you for matches at eleven fifty. You can confirm she was steady or claim you do not remember.",
      actions = listOf(
        GameBeatAction("confirm_alive", "Confirm alive"),
        GameBeatAction("forget", "Forget"),
        GameBeatAction("sell_to_host", "Sell to Host"),
      ),
      is_optional = true,
    ),
    GameBeat(30, "the_maid", "TWIST",
      "The note is still in the mirror's edge if no one has cleaned the powder room yet.",
      actions = listOf(
        GameBeatAction("retrieve", "Retrieve it"),
        GameBeatAction("tell_sister", "Tell Sister"),
        GameBeatAction("leave", "Leave it"),
      ),
      is_optional = true,
    ),
    GameBeat(30, "all", "CLOCK",
      "Half past midnight. The valet should have been back twenty minutes ago. The kitchen garden door is unlatched."),
    GameBeat(33, "all", "NARRATIVE",
      "The band starts a slow number. Across the lawn, a single yellow light moves on the Sound."),
    GameBeat(38, "the_host", "TWIST",
      "The Husband is looking at your hair, then at the lawn, then at your hair again.",
      actions = listOf(
        GameBeatAction("apologize", "Apologize"),
        GameBeatAction("redirect_bootlegger", "Blame Bootlegger"),
        GameBeatAction("buy_time", "Stall"),
      ),
    ),
    GameBeat(44, "the_doctor", "TWIST",
      "What the Husband asked you last week comes back into focus when you look at him now.",
      actions = listOf(
        GameBeatAction("say_aloud", "Say aloud"),
        GameBeatAction("ask_him", "Ask him"),
        GameBeatAction("withhold", "Withhold"),
      ),
      is_optional = true,
    ),
    GameBeat(45, "all", "CLOCK",
      "Quarter to one. If she was alive at eleven forty, this stops being a body case at the next sentence one of you speaks."),
    GameBeat(46, "the_aviator", "TWIST",
      "Your appointment at the Glen Cove airfield is in less than two hours. The passenger has not arrived.",
      actions = listOf(
        GameBeatAction("warn_host", "Warn Host"),
        GameBeatAction("leave_now", "Leave now"),
        GameBeatAction("wait", "Wait"),
      ),
      is_optional = true,
    ),
    GameBeat(46, "the_sister", "TWIST",
      "The Journalist's notebook is on the side table. Three pages from the top is the headline.",
      actions = listOf(
        GameBeatAction("remove", "Take a page"),
        GameBeatAction("distract", "Distract her"),
        GameBeatAction("leave_alone", "Leave alone"),
      ),
    ),
    GameBeat(48, "the_photographer", "DEAD_DROP",
      "Cross to the side table. Slip the plate face-up under the candlestick. Walk away.",
      host_note = "Pre-place a small printed photograph next to the candle. Photographer leaves it visible.",
      is_optional = true,
    ),
    GameBeat(48, "the_photographer", "TWIST",
      "The plate of the Host and the socialite on the terrace is in your case. Sell it once, to the right hand.",
      actions = listOf(
        GameBeatAction("offer_host", "Offer Host"),
        GameBeatAction("offer_paper", "Offer paper"),
        GameBeatAction("show_room", "Show the room"),
      ),
      is_optional = true,
    ),
    GameBeat(50, "the_driver", "GATHER_INTEL",
      "Excuse yourself to the back gate. Walk the perimeter. Three minutes. Confirm whether the second car is still parked beyond the hedge.",
      host_note = "He saw the getaway car. Whether he returns with that information is his choice.",
      is_optional = true,
    ),
    GameBeat(50, "the_driver", "TWIST",
      "If you say what you saw at the back gate, the Husband makes you next week. If you do not, the Host keeps you.",
      actions = listOf(
        GameBeatAction("tell_husband", "Tell Husband"),
        GameBeatAction("tell_host", "Tell Host"),
        GameBeatAction("withhold", "Withhold"),
      ),
      is_optional = true,
    ),
    GameBeat(54, "all", "NARRATIVE",
      "The clock in the hall reads ten past one. The valet has not returned."),
    GameBeat(60, "all", "CLOCK",
      "One o'clock. If she has not been seen by now, she is not on this property. The genre is about to change."),
    GameBeat(60, "the_husband", "TWIST",
      "If she was alive at eleven forty, this is not a body case. It is a leaving case.",
      actions = listOf(
        GameBeatAction("say_aloud", "Say it aloud"),
        GameBeatAction("confront_host", "Confront Host"),
        GameBeatAction("save_for_dawn", "Save for dawn"),
      ),
    ),
    GameBeat(68, "the_aviator", "RENDEZVOUS",
      "Meet the Host in the kitchen for two minutes. The kitchen is two doors down. Decide together whether the appointment is on.",
      host_note = "Paired beat. Two empty chairs.",
      is_optional = true,
    ),
    GameBeat(68, "the_host", "RENDEZVOUS",
      "Meet the Aviator in the kitchen for two minutes. Decide whether the appointment is on.",
    ),
    GameBeat(68, "the_host", "TWIST",
      "Three more hours. That is all you need. Buy them.",
      actions = listOf(
        GameBeatAction("offer_journalist", "Offer Journalist"),
        GameBeatAction("blame_sister", "Blame Sister"),
        GameBeatAction("confess_quietly", "Confess quietly"),
      ),
    ),
    GameBeat(75, "all", "CLOCK",
      "Quarter past one. Forty-five minutes until the papers go to bed. The Host needs the airfield to be in the air by two."),
    GameBeat(76, "all", "NARRATIVE",
      "The band stops mid-song outside. Someone has asked them to."),
    GameBeat(80, "all", "NARRATIVE",
      "Name what you think happened. Write it on the corner of a cocktail napkin and place it on the side table.",
      host_note = "Hand out napkins and pens. Do not let anyone write until you have read this aloud."),
    GameBeat(90, "all", "REVEAL",
      "She vanished by her own choice, with help.\n\nThe Sister knew. The note in the powder room was the instruction. The Host had agreed weeks ago to drive the car waiting at the back of the property; when she did not appear at the meeting point at midnight, he panicked and stayed at the party to misdirect. The figure on the lawn the Husband saw was the Host going to look for her at eleven forty — the Husband's eyes were not what they were and the Aviator's hair muddied the recall. The Bootlegger saw her speak with the Husband and walk away alive at eleven forty. She left under her own power at twelve oh five through the kitchen garden.\n\nThe second car at the back gate was a Ford coupe, driven by the Host's chauffeur, who had been instructed two days earlier to wait there from eleven thirty to one. The Driver — if at the table — saw it from the perimeter and chose which employer to keep. The Aviator's appointment was the next leg of her route, out of Glen Cove at two in the morning.\n\nThe Journalist's headline was about the affair in 1922, not the disappearance tonight. The Husband is right that this is not a body case. The Host bought the three hours she needed.\n\nShe is somewhere else by morning. The Sister will not say where.",
      killer_character_id = "the_host",
      ending_id = "engineered_disappearance",
      host_note = "Read with the band silent. Pause five seconds after \"under her own power.\" Look at the Sister last."),
  ),
)
