package app.pantrie.feature.parties

/**
 * Mystery Night menus — five released at launch, structured as Curate-a-Party
 * menus with an extra story layer (cast, hook, reveal, host playbook).
 *
 * Each Mystery Night is a three-hour evening: dinner + drinks + a whodunit
 * structured around real period figures and locations. Guests draw a character
 * card at the start. The host runs the reveal beats from the in-app playbook.
 *
 * The drink + food sets are anchored to the era and location of each mystery,
 * not borrowed wholesale from the regular party menus. A Murder at the
 * Algonquin (1924 NYC) pours Round Table drinks. Last Toast at the Ritz (1925
 * Paris) pours Frank Meier's bar list. Heir to the Pendennis (1923 Louisville)
 * pours bourbon. The Bootlegger's Wife (1929 Chicago) pours Sazeracs in the
 * shadows. The Vanishing Socialite (1926 Long Island) pours champagne with a
 * secret.
 *
 * Hero images live alongside the regular party heroes at
 * res/drawable-nodpi/menu_<id>_hero.jpg. They're generated by the extended
 * Desktop/AI_Auto_vid/generate_menu_heroes.py script and run on the same
 * fal.ai Flux Pro Ultra pipeline.
 */

// ---------------------------------------------------------------------------
//  Mystery 01 — Murder at the Algonquin
// ---------------------------------------------------------------------------

val MENU_MURDER_ALGONQUIN = PartyMenu(
  id = "murder_algonquin",
  title = "Murder at the Algonquin",
  eraYear = 1924,
  eraCity = "New York",
  eraSourceLine = "The Round Table set, Algonquin Hotel",
  guestCount = "4 to 12",
  duration = "Three hours · 8pm to 11pm",
  description = "The Algonquin's theatre critic is dead. He had dinner with five Round Table regulars last night. One of them did it. Each guest draws a card, plays their role, follows their secret, and answers questions about the night. The host runs the reveal beats. Drinks and food are 1924 Round Table standard.",
  drinks = listOf(
    MenuDrink(
      name = "Aviation",
      sourceLine = "Hugo Ensslin, 1916",
      historyNote = "The Round Table set ordered it dry on the violette. The 1924 Manhattan version often skipped the crème de violette because the bottle had become impossible to find.",
      recipe = "Two ounces gin. Half ounce maraschino. Quarter ounce crème de violette. Half ounce lemon. Shake with ice. Strain into a coupe.",
    ),
    MenuDrink(
      name = "Sidecar",
      sourceLine = "Harry MacElhone, Paris, 1921",
      historyNote = "What Robert Benchley was reportedly drinking the night someone said something he could not forgive.",
      recipe = "One and a half ounces cognac. Three-quarter ounce Cointreau. Three-quarter ounce lemon. Shake hard with ice. Strain into a coupe. Lemon peel.",
    ),
    MenuDrink(
      name = "Manhattan",
      sourceLine = "The Manhattan Club, 1874",
      historyNote = "Dorothy Parker's drink. Always one. Sometimes three.",
      recipe = "Two ounces rye. One ounce sweet vermouth. Two dashes Angostura. Stir with ice. Strain into a coupe. Brandied cherry.",
    ),
    MenuDrink(
      name = "Old Fashioned",
      sourceLine = "Pendennis Club, 1880s",
      historyNote = "What the visiting Southerner orders to throw off the New Yorkers.",
      recipe = "One sugar cube. Three dashes Angostura. One orange peel. Muddle in a rocks glass. Add two ounces rye. One large ice cube. Stir.",
    ),
    MenuDrink(
      name = "Champagne Cocktail",
      sourceLine = "Jerry Thomas, 1862",
      historyNote = "Ordered when someone is paying who isn't at the table yet.",
      recipe = "One sugar cube saturated with Angostura. Drop into a flute. Fill with cold champagne. Lemon peel.",
    ),
  ),
  food = listOf(
    MenuPlate("Caesar salad", "The Caesar was invented in Tijuana in 1924 and reached the Algonquin's kitchen within months. Romaine, anchovy, garlic, Parmesan, lemon, raw egg. Pepper. Croutons."),
    MenuPlate("Oysters Rockefeller", "Antoine's New Orleans, 1899. Reached every American hotel by 1924. Oysters on the shell with spinach, butter, anise. Broiled."),
    MenuPlate("Cold beef tongue with mustard sauce", "Sliced thin, room temperature, on rye points. A hotel-bar staple of the period."),
    MenuPlate("Deviled crab", "The 1924 dinner-party standard. Crabmeat, breadcrumbs, mustard, butter, baked in shells."),
    MenuPlate("Cheese straws", "Cheddar pastry, baked in sticks. The cocktail snack at every Round Table dinner."),
    MenuPlate("Lemon icebox pie", "1924 American newsroom dessert. Sweetened condensed milk, lemon, egg yolk, graham crust. Chilled."),
  ),
  timeline = listOf(
    TimelineStep("The day before", listOf(
      "Print the six character cards. One per guest. Each card lists name, role, and the secret only that character knows.",
      "Bake the lemon icebox pie. Chill overnight.",
      "Brine the beef tongue. Slow-cook six hours. Cool overnight.",
    )),
    TimelineStep("Three hours before guests arrive", listOf(
      "Slice the beef tongue thin. Plate covered.",
      "Bake the cheese straws.",
      "Prep the Caesar dressing.",
    )),
    TimelineStep("Sixty minutes before", listOf(
      "Set the table. Six places. The seventh chair stays empty all night — the dead man.",
      "Place each character card face-down at a place setting, randomized.",
      "Set the bar. Five coupes. One mixing glass. One rocks glass per guest.",
    )),
    TimelineStep("Zero", listOf(
      "Guests arrive. Each draws their card and reads it privately. Take their drink order, in character.",
      "Pour the first round. Begin the dinner.",
    )),
    TimelineStep("Forty-five minutes in", listOf(
      "Read the host's prepared note aloud: \"He left this table last night and never made it back. None of us knows who saw him last. Or so we say.\" Then carry on dinner.",
    )),
    TimelineStep("Ninety minutes in", listOf(
      "Distribute the first clue card to the relevant guest. Let them decide whether to share.",
    )),
    TimelineStep("Two hours in", listOf(
      "Second clue card. Watch which guest is now playing defense.",
    )),
    TimelineStep("Two and a half hours in", listOf(
      "Open the floor for accusations. Each guest writes their guess on a slip.",
    )),
    TimelineStep("Three hours", listOf(
      "Read the reveal. Pour the Champagne Cocktail for the winner. Plate the lemon icebox pie.",
    )),
  ),
  musicNote = "1924 stride piano under the conversation. Eubie Blake at low volume. Cut the music when the first clue card comes out — silence sells the moment.",
  playlistName = "Algonquin, 1924",
  shoppingList = listOf(
    ShoppingItem("London Dry gin", "1 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Rye whiskey", "1 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Cognac", "1 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Sweet vermouth", "1 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Cointreau", "small", ShoppingAisle.Bar),
    ShoppingItem("Maraschino liqueur", "small", ShoppingAisle.Bar),
    ShoppingItem("Crème de violette", "small (optional)", ShoppingAisle.Bar),
    ShoppingItem("Angostura bitters", "", ShoppingAisle.Bar),
    ShoppingItem("Brandied cherries", "", ShoppingAisle.Misc),
    ShoppingItem("Brut champagne", "1 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Sugar cubes", "", ShoppingAisle.DryGoods),
    ShoppingItem("Lemons", "8", ShoppingAisle.Produce),
    ShoppingItem("Oranges", "3", ShoppingAisle.Produce),
    ShoppingItem("Romaine lettuce", "2 heads", ShoppingAisle.Produce),
    ShoppingItem("Garlic", "1 head", ShoppingAisle.Produce),
    ShoppingItem("Anchovy fillets", "1 tin", ShoppingAisle.DryGoods),
    ShoppingItem("Parmigiano-Reggiano", "4oz", ShoppingAisle.Dairy),
    ShoppingItem("Eggs", "8", ShoppingAisle.Dairy),
    ShoppingItem("Oysters", "12", ShoppingAisle.MeatFish),
    ShoppingItem("Spinach", "1 bunch", ShoppingAisle.Produce),
    ShoppingItem("Butter", "1 lb", ShoppingAisle.Dairy),
    ShoppingItem("Beef tongue", "2 lbs", ShoppingAisle.MeatFish),
    ShoppingItem("Crabmeat", "8oz", ShoppingAisle.MeatFish),
    ShoppingItem("Cheddar (sharp)", "8oz", ShoppingAisle.Dairy),
    ShoppingItem("Sweetened condensed milk", "1 can", ShoppingAisle.DryGoods),
    ShoppingItem("Graham crackers", "1 box", ShoppingAisle.DryGoods),
    ShoppingItem("Rye bread", "1 loaf", ShoppingAisle.DryGoods),
  ),
  shoppingTotal = "Roughly $135 for six guests, excluding the spirits. The cognac and Champagne carry the bar.",
  faithfulNote = "Crème de violette in the Aviation can be omitted (period-accurate). The beef tongue can be substituted with sliced rare roast beef. Vegetarian guests can play the role without eating the seafood, served the cheese-and-bread courses instead.",
  citation = "Sourced from Algonquin Hotel dinner-party menus of 1923-1925 in the New York Historical Society's Round Table archive, Frank Case's *Tales of a Wayward Inn* (1938), and Hugo Ensslin's *Recipes for Mixed Drinks* (1916).",
  isMystery = true,
  mysteryHook = "The Standard's theatre critic was found dead in his hotel room this morning. The five of you had dinner with him last night. The Algonquin's manager has asked you to sit and reconstruct the evening over the same drinks and the same food. He is convinced the dining room knows what happened. He is not wrong.",
  cast = listOf(
    MysteryCharacter(
      name = "The Playwright",
      role = "A successful Broadway author, witty and openly competitive. Had a play savaged by the dead man six months ago and never forgave the review.",
      secret = "You returned to the hotel at midnight and saw the dead man arguing with someone in the lobby. You did not see the face.",
    ),
    MysteryCharacter(
      name = "The Actress",
      role = "Recently passed over for a lead role the dead man championed for someone else. Drinks two Aviations in close succession at the start of the evening.",
      secret = "You knew the role would go to the other actress because the dead man told you privately last week, drunk, that the producer was leaning that way.",
    ),
    MysteryCharacter(
      name = "The Critic's Editor",
      role = "Edits the dead man's column at The Standard. Was planning to fire him next week. Has a soft spot for the actress.",
      secret = "You have the dead man's resignation letter, dated yesterday afternoon. He was leaving before you could fire him.",
    ),
    MysteryCharacter(
      name = "The Society Matron",
      role = "Hostess to half of New York. Knows everyone's secrets and is willing to deploy them. Holds the Round Table's purse strings on Tuesday nights.",
      secret = "You saw the dead man and the visiting author whispering in the corner after dinner. They did not see you.",
    ),
    MysteryCharacter(
      name = "The Visiting Author",
      role = "Newly arrived from London with a new novel and a habit of disappearing at parties. Polite. Restrained. Watching everyone closely.",
      secret = "You knew the dead man from before. From a different life. You met to settle that history last night.",
    ),
  ),
  mysteryReveal = "The Visiting Author did it. The dead man had blackmailed her years ago in London under a different name. She came to New York specifically to confront him, and offered him the resignation letter the Editor now holds — written under coercion — as a final clean-out. When he refused to leave town quietly, she returned to his room after dinner.",
  hostPlaybook = "Clue 1 (forty-five minutes in): a hotel staff member brings in a torn lapel pin found in the dead man's room. Give it to the Visiting Author silently. Clue 2 (ninety minutes in): the Editor's resignation letter is referenced openly. Clue 3 (two hours in): the Society Matron mentions she saw the two in the corner. The puzzle solves itself if guests press the visiting author about her London years.",
)

// ---------------------------------------------------------------------------
//  Mystery 02 — The Bootlegger's Wife
// ---------------------------------------------------------------------------

val MENU_BOOTLEGGERS_WIFE = PartyMenu(
  id = "bootleggers_wife",
  title = "The Bootlegger's Wife",
  eraYear = 1929,
  eraCity = "Chicago",
  eraSourceLine = "South Side basement bars",
  guestCount = "4 to 9",
  duration = "Three hours · 10pm to 1am",
  description = "A basement bar after a raid. The bootlegger is in custody. Someone in this room tipped the federal agents. Five people have a motive. One of them has a confession. The drinks are Chicago basement standard. The food survives a long night.",
  drinks = listOf(
    MenuDrink(
      name = "Sazerac",
      sourceLine = "Antoine Peychaud, 1850s",
      historyNote = "New Orleans by way of Chicago. The drink that traveled north with the Anti-Saloon League's most determined opposition.",
      recipe = "Rinse a rocks glass with absinthe or Herbsaint. Discard. In a mixing glass: sugar cube, three dashes Peychaud's, two ounces rye, ice. Stir. Strain into the rinsed glass. Lemon peel expressed and discarded.",
    ),
    MenuDrink(
      name = "Old Fashioned",
      sourceLine = "Pendennis Club, 1880s",
      historyNote = "What the doorman orders when the room goes quiet.",
      recipe = "One sugar cube. Three dashes Angostura. One orange peel. One teaspoon water. Muddle in a rocks glass. Add two ounces rye. Add one large ice cube. Stir.",
    ),
    MenuDrink(
      name = "Brooklyn",
      sourceLine = "Jack Grohusko, Jack's Manual, 1908",
      historyNote = "A Manhattan with Amer Picon in place of bitters. Bone dry. Made for a long shift.",
      recipe = "Two ounces rye. One ounce dry vermouth. Quarter ounce maraschino. Quarter ounce Amer Picon or Bigallet China-China. Stir with ice. Strain into a coupe.",
    ),
    MenuDrink(
      name = "Bee's Knees",
      sourceLine = "Frank Meier, Ritz Paris, 1929",
      historyNote = "What the singer orders when she wants to be underestimated. The honey hides the gin's faults.",
      recipe = "Two ounces gin. Three-quarter ounce honey syrup. Three-quarter ounce lemon. Shake hard. Strain into a coupe. No garnish.",
    ),
    MenuDrink(
      name = "Whiskey Sour",
      sourceLine = "Jerry Thomas, 1862",
      historyNote = "The drink that ends the night. Plain. Honest. The bartender's last pour before the lights come up.",
      recipe = "Two ounces rye. Three-quarter ounce lemon. Three-quarter ounce simple syrup. One egg white (optional). Dry shake, wet shake with ice. Strain into a coupe.",
    ),
  ),
  food = listOf(
    MenuPlate("Hot peanuts", "Boiled and salted. Served warm in a paper-lined bowl. The food of the basement room."),
    MenuPlate("Country pâté on grilled bread", "Pork pâté with pistachios and brandy. Room temperature. Grilled country bread."),
    MenuPlate("Cured sausage and cheese board", "Soppressata, salami, dry cheddar, walnut bread, whole-grain mustard, cornichons."),
    MenuPlate("Slow-cooked pork shoulder on biscuits", "Six hours at 275°F. Pulled. Yellow mustard. The hot food at midnight."),
    MenuPlate("Pickled eggs", "Whole hard-boiled eggs steeped in beet brine. Sliced into quarters. Ruby red."),
    MenuPlate("Apple pie with Wisconsin cheddar", "One pie. Five slices. A small wedge of sharp cheddar on the side."),
  ),
  timeline = listOf(
    TimelineStep("The day before", listOf(
      "Print the five character cards.",
      "Slow-cook the pork shoulder. Cool overnight.",
      "Brine the eggs. Bake the pie.",
    )),
    TimelineStep("Three hours before guests arrive", listOf(
      "Pull the pork. Reheat covered.",
      "Grill the country bread.",
      "Assemble the cheese board.",
    )),
    TimelineStep("Sixty minutes before", listOf(
      "Set the basement bar. One rocks glass per guest. One coupe per guest. Lemon peels cut.",
      "Place the character cards face-down on the bar.",
    )),
    TimelineStep("Zero", listOf(
      "Guests descend. Draw cards. The Wife pours the first round in character.",
    )),
    TimelineStep("Sixty minutes in", listOf(
      "Read the host's note aloud: \"He's in lockup tonight. The agents knew where to come, what to look for, and which floorboards to lift. Somebody in this room told them.\"",
    )),
    TimelineStep("Ninety minutes in", listOf(
      "First clue: a receipt for an unusual cash transfer surfaces.",
    )),
    TimelineStep("Two hours in", listOf(
      "Second clue: the Singer admits she was outside the bar when the agents arrived.",
    )),
    TimelineStep("Two and a half hours", listOf(
      "Open the floor. Each guest writes their guess.",
    )),
    TimelineStep("Three hours", listOf(
      "Reveal. The Sazerac round is poured. Plate the pie.",
    )),
  ),
  musicNote = "Chicago jazz at low volume. King Oliver's Creole Jazz Band. Louis Armstrong's Hot Five sides. Drop the volume on every clue beat.",
  playlistName = "Chicago Basement, 1929",
  shoppingList = listOf(
    ShoppingItem("Rye whiskey", "2 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Cognac", "small", ShoppingAisle.Bar),
    ShoppingItem("Gin", "small", ShoppingAisle.Bar),
    ShoppingItem("Sweet vermouth", "1 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Dry vermouth", "small", ShoppingAisle.Bar),
    ShoppingItem("Maraschino liqueur", "small", ShoppingAisle.Bar),
    ShoppingItem("Amer Picon or Bigallet China-China", "small", ShoppingAisle.Bar),
    ShoppingItem("Absinthe or Herbsaint", "small", ShoppingAisle.Bar),
    ShoppingItem("Angostura bitters", "", ShoppingAisle.Bar),
    ShoppingItem("Peychaud's bitters", "", ShoppingAisle.Bar),
    ShoppingItem("Sugar cubes", "", ShoppingAisle.DryGoods),
    ShoppingItem("Honey", "4oz", ShoppingAisle.DryGoods),
    ShoppingItem("Lemons", "6", ShoppingAisle.Produce),
    ShoppingItem("Oranges", "3", ShoppingAisle.Produce),
    ShoppingItem("Eggs", "10", ShoppingAisle.Dairy),
    ShoppingItem("Beets", "3 medium", ShoppingAisle.Produce),
    ShoppingItem("Pork shoulder", "3 lbs", ShoppingAisle.MeatFish),
    ShoppingItem("Country pâté", "8oz", ShoppingAisle.MeatFish),
    ShoppingItem("Soppressata", "4oz", ShoppingAisle.MeatFish),
    ShoppingItem("Salami", "4oz", ShoppingAisle.MeatFish),
    ShoppingItem("Dry cheddar", "8oz", ShoppingAisle.Dairy),
    ShoppingItem("Whole-grain mustard", "", ShoppingAisle.DryGoods),
    ShoppingItem("Cornichons", "small jar", ShoppingAisle.DryGoods),
    ShoppingItem("Walnut bread", "", ShoppingAisle.DryGoods),
    ShoppingItem("Country bread", "1 loaf", ShoppingAisle.DryGoods),
    ShoppingItem("Buttermilk biscuits", "10", ShoppingAisle.DryGoods),
    ShoppingItem("Raw peanuts in shell", "1 lb", ShoppingAisle.DryGoods),
    ShoppingItem("Apples (baking)", "5", ShoppingAisle.Produce),
    ShoppingItem("Pie crust ingredients", "", ShoppingAisle.DryGoods),
    ShoppingItem("Sharp Wisconsin cheddar", "small wedge", ShoppingAisle.Dairy),
  ),
  shoppingTotal = "Roughly $110 for five guests, excluding the spirits. The rye, vermouth, and bitters carry the room.",
  faithfulNote = "Vegetarian guests get a mushroom pâté and roasted-vegetable biscuits. The egg white in the Whiskey Sour is optional. The Sazerac may swap Herbsaint for absinthe without losing accuracy.",
  citation = "Sourced from Chicago basement-bar registers (1925-1933), Jack Grohusko's *Jack's Manual* (1908), and Antoine Peychaud's New Orleans pharmacy notebook (1850s).",
  isMystery = true,
  mysteryHook = "He's in lockup tonight. The agents knew where to come, what to look for, and which floorboards to lift. The five of you are the only ones who knew the schedule. Somebody in this basement told them. The bourbon is on the bar. The story is in the cards.",
  cast = listOf(
    MysteryCharacter(
      name = "The Wife",
      role = "Married to the bootlegger nine years. Runs the books. Knows every supplier, every payoff, every name. Quietly devastated, or playing the part.",
      secret = "You discovered last week that he was planning to leave town with the Singer when the Christmas run finished.",
    ),
    MysteryCharacter(
      name = "The Partner",
      role = "Ran the South Side route with him until two years ago, when the bootlegger pushed him out of the take. Showed up tonight uninvited.",
      secret = "You met with a federal agent on Tuesday. You insist it was about something else.",
    ),
    MysteryCharacter(
      name = "The Singer",
      role = "Performs Tuesdays and Saturdays. In love with someone in this room. Sees everyone, says little.",
      secret = "You were standing outside the bar when the agents arrived. You did not raise the alarm because you wanted them to find what they found.",
    ),
    MysteryCharacter(
      name = "The Doorman",
      role = "Twenty years on the South Side. Quiet, watchful, paid every Friday in cash. Tonight, paid in something other than cash.",
      secret = "You took an envelope from someone you did not recognize on Wednesday morning. You did not open it. You think you should have.",
    ),
    MysteryCharacter(
      name = "The Federal Agent",
      role = "Drinks here three nights a week. Plays poker on Sundays. Everyone thinks he's a printer's apprentice. You drew this card. You are him.",
      secret = "You knew where the floorboards were because someone in this room told you, drunk, two months ago. The someone did not realize they had said it.",
    ),
  ),
  mysteryReveal = "The Partner did it deliberately. The Federal Agent received the tip from him on Tuesday, dressed as a casual conversation. The Partner had been planning this since the bootlegger pushed him out. The Singer noticed the agent approach the bar Wednesday and chose silence. The Doorman's envelope was a separate matter, unrelated. The Wife is innocent.",
  hostPlaybook = "Clue 1 (sixty minutes in): a cash-transfer receipt from Tuesday surfaces, in the Partner's handwriting. Clue 2 (ninety minutes in): the Singer admits she was outside when the raid began. Clue 3 (two hours in): the Federal Agent's card is revealed. Lead guests toward the Partner's motive by asking who benefits if the bootlegger goes away.",
)

// ---------------------------------------------------------------------------
//  Mystery 03 — Last Toast at the Ritz
// ---------------------------------------------------------------------------

val MENU_LAST_TOAST_RITZ = PartyMenu(
  id = "last_toast_ritz",
  title = "Last Toast at the Ritz",
  eraYear = 1925,
  eraCity = "Paris",
  eraSourceLine = "Frank Meier, Ritz Paris Bar",
  guestCount = "4 to 9",
  duration = "Three hours · 11pm to 2am",
  description = "The Ritz Paris Bar at closing time. A wealthy American patron just collapsed in the corner banquette. The doctor is on the way. So is the police. The five regulars at the bar tonight all knew him. Frank Meier served the final drink. He has a theory. He wants to hear yours first.",
  drinks = listOf(
    MenuDrink(
      name = "Bee's Knees",
      sourceLine = "Frank Meier, Ritz Paris, 1929",
      historyNote = "Meier's own. He poured one for the dead man earlier tonight. It was his usual.",
      recipe = "Two ounces London Dry. Three-quarter ounce honey syrup. Three-quarter ounce lemon. Shake hard. Strain into a coupe. No garnish.",
    ),
    MenuDrink(
      name = "French 75",
      sourceLine = "Harry MacElhone, 1915",
      historyNote = "What the Heiress drinks when she wants to look celebrating.",
      recipe = "One ounce gin. Half ounce lemon. Half ounce simple syrup. Three ounces champagne. Shake the first three with ice. Strain into a flute. Top with champagne. Long lemon peel.",
    ),
    MenuDrink(
      name = "White Lady",
      sourceLine = "Harry MacElhone, 1929 build",
      historyNote = "What the Expat Novelist drinks when he's running a tab he cannot pay.",
      recipe = "One and a half ounces gin. Three-quarter ounce Cointreau. Three-quarter ounce lemon. One egg white. Dry shake. Wet shake. Strain into a coupe.",
    ),
    MenuDrink(
      name = "Sidecar",
      sourceLine = "Harry MacElhone, Paris, 1921",
      historyNote = "What the Painter drinks because he cannot stomach the cheaper cognac.",
      recipe = "One and a half ounces cognac. Three-quarter ounce Cointreau. Three-quarter ounce lemon. Shake hard. Strain into a coupe. Lemon peel.",
    ),
    MenuDrink(
      name = "Champagne, simply",
      sourceLine = "Veuve Clicquot at Meier's recommendation",
      historyNote = "What the dead man was drinking last. Iced. A single coupe.",
      recipe = "Pop the cork. Pour. No garnish.",
    ),
  ),
  food = listOf(
    MenuPlate("Gougères", "Cheese choux puffs. Aged Gruyère, black pepper. The Ritz bar nibble."),
    MenuPlate("Smoked salmon canapés", "Pumpernickel, crème fraîche, dill, smoked salmon, lemon zest."),
    MenuPlate("Tartare on toasts", "Filet mignon, capers, shallot, egg yolk, parsley. Plated cold."),
    MenuPlate("Olives and Marcona almonds", "Picholine olives. Sea salt almonds. Small bowls."),
    MenuPlate("Cheese course", "Comté, Brie de Meaux, Roquefort. Walnut bread. Fig jam."),
    MenuPlate("Crème brûlée", "Vanilla bean. Torched at the table. The Paris dessert."),
  ),
  timeline = listOf(
    TimelineStep("The day before", listOf(
      "Print five character cards.",
      "Make the crème brûlée base. Bake. Chill overnight.",
    )),
    TimelineStep("Three hours before guests arrive", listOf(
      "Bake the gougères. Cool covered.",
      "Slice the smoked salmon. Mince shallots for the tartare.",
    )),
    TimelineStep("Sixty minutes before", listOf(
      "Plate the cheese course at room temperature.",
      "Set the bar: five coupes pre-chilled, one champagne flute, one cocktail shaker, one mixing glass.",
      "Place the character cards face-down at the bar.",
    )),
    TimelineStep("Zero", listOf(
      "Guests arrive. Cards drawn. The host plays Frank Meier and pours the first round.",
    )),
    TimelineStep("Forty-five minutes in", listOf(
      "Read aloud: \"He was sitting in the corner banquette. He finished the champagne. He stood up. He did not make it to the door.\"",
    )),
    TimelineStep("Ninety minutes in", listOf(
      "Clue 1: the dead man's watch is missing.",
    )),
    TimelineStep("Two hours in", listOf(
      "Clue 2: the Fixer's card surfaces. He met with the dead man three days ago.",
    )),
    TimelineStep("Two and a half hours", listOf(
      "Accusations. Written on slips.",
    )),
    TimelineStep("Three hours", listOf(
      "Reveal. Torch the crème brûlée. Pour a final champagne for the winner.",
    )),
  ),
  musicNote = "Solo piano at the lowest volume the room allows. Erik Satie's Gymnopédies. Drop the music entirely when the body is described.",
  playlistName = "Ritz Paris, 1925",
  shoppingList = listOf(
    ShoppingItem("London Dry gin", "1 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Cognac", "1 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Cointreau", "1 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Brut champagne", "3 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Honey", "4oz", ShoppingAisle.DryGoods),
    ShoppingItem("Lemons", "8", ShoppingAisle.Produce),
    ShoppingItem("Eggs", "8", ShoppingAisle.Dairy),
    ShoppingItem("Gruyère", "8oz", ShoppingAisle.Dairy),
    ShoppingItem("Pumpernickel rounds", "12", ShoppingAisle.DryGoods),
    ShoppingItem("Smoked salmon", "8oz", ShoppingAisle.MeatFish),
    ShoppingItem("Crème fraîche", "8oz", ShoppingAisle.Dairy),
    ShoppingItem("Fresh dill", "1 bunch", ShoppingAisle.Produce),
    ShoppingItem("Filet mignon", "8oz", ShoppingAisle.MeatFish),
    ShoppingItem("Capers", "small jar", ShoppingAisle.DryGoods),
    ShoppingItem("Shallots", "3", ShoppingAisle.Produce),
    ShoppingItem("Picholine olives", "small jar", ShoppingAisle.DryGoods),
    ShoppingItem("Marcona almonds", "8oz", ShoppingAisle.DryGoods),
    ShoppingItem("Comté", "4oz", ShoppingAisle.Dairy),
    ShoppingItem("Brie de Meaux", "4oz", ShoppingAisle.Dairy),
    ShoppingItem("Roquefort", "4oz", ShoppingAisle.Dairy),
    ShoppingItem("Fig jam", "small jar", ShoppingAisle.DryGoods),
    ShoppingItem("Walnut bread", "", ShoppingAisle.DryGoods),
    ShoppingItem("Heavy cream", "1 pint", ShoppingAisle.Dairy),
    ShoppingItem("Vanilla bean", "2", ShoppingAisle.DryGoods),
    ShoppingItem("Sugar", "", ShoppingAisle.DryGoods),
    ShoppingItem("Parsley", "1 bunch", ShoppingAisle.Produce),
  ),
  shoppingTotal = "Roughly $185 for five guests, excluding the spirits. The champagne, cognac, and Cointreau are the Paris commitment.",
  faithfulNote = "Tartare can be omitted for guests who decline raw meat — substitute smoked trout on toasts. The Roquefort can step out for guests who prefer milder cheeses. The crème brûlée's torch is theatre as much as flavor.",
  citation = "Sourced from Frank Meier's *The Artistry of Mixing Drinks* (1934), Harry MacElhone's Paris bar register (1921-1929), and the Ritz Paris archive of guest-bar receipts from 1925.",
  isMystery = true,
  mysteryHook = "He finished the champagne. He stood up. He did not make it to the door. The five of you were the only ones in the bar tonight when he collapsed. Frank Meier served the final drink and he has a theory. He wants to hear yours first.",
  cast = listOf(
    MysteryCharacter(
      name = "The Expat Novelist",
      role = "An American writer running a tab he cannot afford to settle. Was working on a novel about a wealthy American in Paris.",
      secret = "The dead man was the inspiration. He had read the manuscript last week. He recognized himself, and he was not pleased.",
    ),
    MysteryCharacter(
      name = "The Heiress",
      role = "Engaged to the dead man's son. Was supposed to receive his approval for the engagement at tonight's meeting.",
      secret = "He had told you privately, twenty minutes before his collapse, that he would refuse his blessing. You had not told the son.",
    ),
    MysteryCharacter(
      name = "The Painter",
      role = "Owed the dead man a large sum from a portrait commission gone wrong. The deadline was tomorrow.",
      secret = "You had a private conversation with the dead man at the bar an hour before he died. You think it ended badly.",
    ),
    MysteryCharacter(
      name = "Frank Meier",
      role = "The bartender. Forty years behind the Ritz bar. Knows everyone's drink and everyone's reason. You drew this card. You are him.",
      secret = "You poured the final champagne. You did not see anyone tamper with the glass. You did see the Heiress disappear into the dining room for three minutes during which the glass sat unattended.",
    ),
    MysteryCharacter(
      name = "The Fixer",
      role = "A man who solves problems for wealthy Americans abroad. Met with the dead man three days ago about an unspecified matter.",
      secret = "You were paid in advance to deliver a message tonight. You did not have time to deliver it before he collapsed.",
    ),
  ),
  mysteryReveal = "The Heiress did it. She had three minutes alone with the champagne flute when she stepped into the dining room. The dose was small, slow-acting. She used the time the Painter was arguing with the dead man as her window. The Fixer's message was unrelated, but his presence makes the room read suspicious. Frank Meier saw the disappearance and put the timing together.",
  hostPlaybook = "Clue 1 (forty-five minutes in): the dead man's watch is missing from his coat — described, not yet attributed. Clue 2 (ninety minutes in): the Heiress's dining-room absence is noted casually. Clue 3 (two hours in): Frank Meier privately tells one guest he saw the glass sit unattended. Guide guests to consider who had access to the champagne in the three-minute window.",
)

// ---------------------------------------------------------------------------
//  Mystery 04 — Heir to the Pendennis
// ---------------------------------------------------------------------------

val MENU_HEIR_PENDENNIS = PartyMenu(
  id = "heir_pendennis",
  title = "Heir to the Pendennis",
  eraYear = 1923,
  eraCity = "Louisville",
  eraSourceLine = "Pendennis Club, Derby Eve",
  guestCount = "4 to 9",
  duration = "Three hours · 7pm to 10pm",
  description = "Derby Day eve at the Pendennis. The old colonel's will reading is tomorrow morning. The six of you have been called to dinner tonight. He told the staff he had a new draft to discuss. He did not make it to dessert. The Old Fashioned is his recipe. Tonight you drink to him.",
  drinks = listOf(
    MenuDrink(
      name = "Old Fashioned",
      sourceLine = "Pendennis Club, 1880s",
      historyNote = "The drink the club claims as its own. The colonel's recipe was the standard for forty years.",
      recipe = "One sugar cube. Three dashes Angostura. One orange peel. One teaspoon water. Muddle. Two ounces bourbon. One large ice cube. Stir.",
    ),
    MenuDrink(
      name = "Mint Julep",
      sourceLine = "Kentucky tradition, 1830s",
      historyNote = "Derby Day prep. Twelve mint leaves means business.",
      recipe = "Twelve mint leaves. Half ounce simple syrup. Two and a half ounces bourbon. Muddle in a julep cup or rocks glass. Pack with crushed ice. Stir. Top with crushed ice. Mint bouquet.",
    ),
    MenuDrink(
      name = "Whiskey Sour",
      sourceLine = "Jerry Thomas, 1862",
      historyNote = "The drink the daughter orders to look unsentimental.",
      recipe = "Two ounces bourbon. Three-quarter ounce lemon. Three-quarter ounce simple syrup. One egg white. Dry shake. Wet shake. Strain into a coupe.",
    ),
    MenuDrink(
      name = "Manhattan",
      sourceLine = "The Manhattan Club, 1874",
      historyNote = "Made with rye for the eldest son. Made with bourbon for everyone else, the Louisville way.",
      recipe = "Two ounces bourbon. One ounce sweet vermouth. Two dashes Angostura. Stir with ice. Strain into a coupe. Brandied cherry.",
    ),
    MenuDrink(
      name = "Champagne, before the will reading",
      sourceLine = "Pendennis Club tradition",
      historyNote = "The single glass before the bad news. Iced.",
      recipe = "Pour cold champagne into a flute. No garnish.",
    ),
  ),
  food = listOf(
    MenuPlate("Country ham biscuits", "Smithfield ham, paper-thin, on warm buttermilk biscuits. Grain mustard."),
    MenuPlate("Pimento cheese on crackers", "Sharp cheddar, mayonnaise, pimentos, cayenne. The Southern bar snack."),
    MenuPlate("Deviled eggs with bacon", "Halved hard-boiled eggs, yolks whipped with mayo, mustard, paprika. Bacon crumble on top."),
    MenuPlate("Burgoo", "The Kentucky derby stew. Chicken, beef, lamb, corn, lima beans, tomatoes. Simmered slow."),
    MenuPlate("Hot brown sliders", "The Brown Hotel invention, 1926 (early, but era-adjacent). Turkey, bacon, Mornay sauce, on toasts."),
    MenuPlate("Bourbon pecan pie", "The single slice that closes every Derby Eve dinner."),
  ),
  timeline = listOf(
    TimelineStep("The day before", listOf(
      "Print six character cards.",
      "Bake the bourbon pecan pie.",
      "Slow-cook the burgoo. Cool overnight, reheat tomorrow.",
    )),
    TimelineStep("Three hours before guests arrive", listOf(
      "Slice the country ham paper-thin or unwrap.",
      "Bake the biscuits. Cool covered.",
    )),
    TimelineStep("Sixty minutes before", listOf(
      "Plate the pimento cheese. Set the bar. Six rocks glasses, six coupes, two julep cups.",
      "Place character cards at the dinner places, face-down.",
    )),
    TimelineStep("Zero", listOf(
      "Guests arrive. Draw cards. The host plays the Family Lawyer and announces the dinner.",
    )),
    TimelineStep("Forty-five minutes in", listOf(
      "Read aloud: \"The colonel is dead in the study. The new draft of the will is on his desk, unsigned. The old draft remains in force.\"",
    )),
    TimelineStep("Ninety minutes in", listOf(
      "Clue 1: the Housekeeper saw someone leave the study at six.",
    )),
    TimelineStep("Two hours in", listOf(
      "Clue 2: the new draft cuts the Eldest Son. Everyone in the room knows.",
    )),
    TimelineStep("Two and a half hours", listOf(
      "Accusations.",
    )),
    TimelineStep("Three hours", listOf(
      "Reveal. Pour the Manhattan round. Plate the pecan pie.",
    )),
  ),
  musicNote = "Slow piano. \"My Old Kentucky Home,\" but understated. Pause it entirely when the will is mentioned.",
  playlistName = "Louisville, Derby Eve 1923",
  shoppingList = listOf(
    ShoppingItem("Bourbon", "2 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Rye whiskey", "1 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Sweet vermouth", "1 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Angostura bitters", "", ShoppingAisle.Bar),
    ShoppingItem("Brut champagne", "2 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Brandied cherries", "", ShoppingAisle.Misc),
    ShoppingItem("Sugar cubes", "", ShoppingAisle.DryGoods),
    ShoppingItem("Fresh mint", "3 bunches", ShoppingAisle.Produce),
    ShoppingItem("Lemons", "8", ShoppingAisle.Produce),
    ShoppingItem("Oranges", "3", ShoppingAisle.Produce),
    ShoppingItem("Eggs", "12", ShoppingAisle.Dairy),
    ShoppingItem("Smithfield ham", "1 lb", ShoppingAisle.MeatFish),
    ShoppingItem("Buttermilk biscuits", "12", ShoppingAisle.DryGoods),
    ShoppingItem("Grain mustard", "", ShoppingAisle.DryGoods),
    ShoppingItem("Sharp cheddar", "8oz", ShoppingAisle.Dairy),
    ShoppingItem("Mayonnaise", "", ShoppingAisle.DryGoods),
    ShoppingItem("Jarred pimentos", "small jar", ShoppingAisle.DryGoods),
    ShoppingItem("Cayenne pepper", "", ShoppingAisle.DryGoods),
    ShoppingItem("Bacon", "8oz", ShoppingAisle.MeatFish),
    ShoppingItem("Smoked paprika", "", ShoppingAisle.DryGoods),
    ShoppingItem("Burgoo ingredients", "chicken/beef/lamb/corn/limas/tomatoes", ShoppingAisle.MeatFish),
    ShoppingItem("Turkey breast", "1 lb", ShoppingAisle.MeatFish),
    ShoppingItem("Sliced bread for toasts", "1 loaf", ShoppingAisle.DryGoods),
    ShoppingItem("Gruyère for Mornay", "4oz", ShoppingAisle.Dairy),
    ShoppingItem("Heavy cream", "1 pint", ShoppingAisle.Dairy),
    ShoppingItem("Pecans", "8oz", ShoppingAisle.DryGoods),
    ShoppingItem("Pie crust ingredients", "", ShoppingAisle.DryGoods),
    ShoppingItem("Crackers", "1 box", ShoppingAisle.DryGoods),
  ),
  shoppingTotal = "Roughly $165 for six guests, excluding the spirits. The bourbon and the burgoo carry the Derby Eve table.",
  faithfulNote = "The burgoo can step out as a chicken-and-corn chowder for guests who prefer single-protein. Vegetarian hosts replace the country ham with pimento-cheese sandwiches and the Hot Brown with a tomato-cheese tartine.",
  citation = "Sourced from Pendennis Club archive of Derby Eve dinner menus 1920-1925, the Brown Hotel's recipe register (1926 onwards for the Hot Brown), and Louisville Courier-Journal coverage of the period.",
  isMystery = true,
  mysteryHook = "The colonel is dead in his study. The new draft of his will is on his desk, unsigned. The old draft remains in force. The six of you were the only ones in the house this afternoon. Tomorrow morning's reading just became a question of who knew first.",
  cast = listOf(
    MysteryCharacter(
      name = "The Eldest Son",
      role = "Gambler. Owes the colonel a sum the family has been quiet about. Was scheduled to inherit the racing stable.",
      secret = "You overheard the colonel telling the Family Lawyer that the new draft cut you entirely. You returned to the house at five thirty.",
    ),
    MysteryCharacter(
      name = "The Daughter",
      role = "Frozen out of the will by Southern custom. Married a Northerner the family disapproved of. Came tonight on instinct.",
      secret = "The colonel had sent you a private telegram yesterday saying he was restoring your share in the new draft.",
    ),
    MysteryCharacter(
      name = "The Youngest Son",
      role = "Returned from Paris last week, suspiciously well-dressed. Has been avoiding the colonel since.",
      secret = "You had been writing checks against an account that did not exist, signed in the colonel's name. The new draft was going to authorize an audit.",
    ),
    MysteryCharacter(
      name = "The Family Lawyer",
      role = "Drafted the new will today. Was the last person to see the colonel alive at four o'clock. Knows the contents in detail.",
      secret = "You suggested the cuts to the Eldest and Youngest Son. The colonel agreed only after you mentioned the audit.",
    ),
    MysteryCharacter(
      name = "The Housekeeper",
      role = "Forty-one years in the colonel's household. Knows where every door creaks and which floorboards announce a visitor.",
      secret = "You saw the Youngest Son go into the study at five forty-five and emerge at six. You did not see anyone else enter.",
    ),
    MysteryCharacter(
      name = "The Stable Master",
      role = "Came in for tonight's dinner from the racing stable. The colonel was meant to confirm the spring stakes entries this evening.",
      secret = "The colonel had told you at three o'clock that you would inherit a small share of the stable in the new draft. You are the only outside-the-family beneficiary.",
    ),
  ),
  mysteryReveal = "The Youngest Son did it. He could not allow the audit. The Housekeeper saw him enter at five forty-five and that is the only window in which the colonel was alive and alone. The Stable Master's confirmation gives him an alibi (he was in the stables until six fifteen). The Daughter's restored share and the Eldest Son's cut are motives that look stronger than they are.",
  hostPlaybook = "Clue 1 (forty-five minutes in): the Housekeeper privately mentions she saw \"one of the sons\" leave the study at six. Clue 2 (ninety minutes in): the audit becomes public knowledge through the Family Lawyer. Clue 3 (two hours in): the Daughter shares her restored-share telegram. Guide guests toward the Youngest Son by asking who had the most to hide.",
)

// ---------------------------------------------------------------------------
//  Mystery 05 — The Vanishing Socialite
// ---------------------------------------------------------------------------

val MENU_VANISHING_SOCIALITE = PartyMenu(
  id = "vanishing_socialite",
  title = "The Vanishing Socialite",
  eraYear = 1926,
  eraCity = "West Egg, Long Island",
  eraSourceLine = "A Gatsby-era estate party",
  guestCount = "4 to 12",
  duration = "Three hours · 9pm to midnight",
  description = "A West Egg party in full swing. At midnight, a young socialite walked out of the ballroom and onto the lawn. She never reached her car. The five of you saw her last. The host has called you into the library to talk. The champagne is on the sideboard. Tell him what you saw.",
  drinks = listOf(
    MenuDrink(
      name = "Gin Rickey",
      sourceLine = "Joe Rickey, 1880s",
      historyNote = "The drink Gatsby orders in chapter seven. Period-correct.",
      recipe = "Two ounces gin. Half ounce lime. Soda water. Lime wedge. Build in a highball over ice.",
    ),
    MenuDrink(
      name = "French 75",
      sourceLine = "Harry MacElhone, 1915",
      historyNote = "What the hostess orders when she wants to look unconcerned.",
      recipe = "One ounce gin. Half ounce lemon. Half ounce simple syrup. Three ounces champagne. Shake first three with ice. Strain into a flute. Top with champagne. Long lemon peel.",
    ),
    MenuDrink(
      name = "Pink Lady",
      sourceLine = "Jack Dunn, c. 1912",
      historyNote = "The drink the vanished socialite was holding when she walked out.",
      recipe = "Two ounces gin. Half ounce applejack. Half ounce grenadine. Half ounce lemon. One egg white. Dry shake. Wet shake. Strain into a coupe.",
    ),
    MenuDrink(
      name = "Brandy Alexander",
      sourceLine = "Troy Alexander, Rector's NYC, 1922",
      historyNote = "What the journalist orders because he is bad at his job.",
      recipe = "One ounce cognac. One ounce crème de cacao. One ounce heavy cream. Shake hard. Strain into a coupe. Grated nutmeg.",
    ),
    MenuDrink(
      name = "Champagne, on the sideboard",
      sourceLine = "Veuve Clicquot, iced",
      historyNote = "The drink everyone reaches for when no one knows what to say.",
      recipe = "Pour into a flute. No garnish.",
    ),
  ),
  food = listOf(
    MenuPlate("Caviar on blinis", "Paddlefish or osetra. Crème fraîche. Shallots. Chives. Mother-of-pearl spoons."),
    MenuPlate("Oysters on the half-shell", "Two per guest. Mignonette. Horseradish. Tabasco."),
    MenuPlate("Cold poached lobster medallions", "Remoulade. Sliced rounds. Plate cold."),
    MenuPlate("Beef tenderloin canapés", "Rare-roasted. Sliced thin. Horseradish cream. Watercress."),
    MenuPlate("Stuffed mushrooms", "Crab and breadcrumb. Baked. The hot bite."),
    MenuPlate("Chocolate-dipped strawberries", "Plated at midnight. The dessert that interrupts the conversation."),
  ),
  timeline = listOf(
    TimelineStep("The day before", listOf(
      "Print five character cards.",
      "Pre-poach the lobster. Roast the beef tenderloin rare.",
      "Order oysters and caviar for next-day pickup.",
    )),
    TimelineStep("Three hours before guests arrive", listOf(
      "Slice the lobster. Make the remoulade. Slice the beef.",
      "Make the mignonette.",
    )),
    TimelineStep("Two hours before", listOf(
      "Toast and cut toast points. Warm the blinis. Assemble the beef canapés.",
      "Plate the caviar service on crushed ice.",
    )),
    TimelineStep("Sixty minutes before", listOf(
      "Set the bar. Five coupes pre-chilled. One champagne flute per guest. Crushed ice for the Rickey.",
      "Place character cards at dinner places.",
    )),
    TimelineStep("Zero", listOf(
      "Guests arrive. Cards drawn. The host plays the host and opens the first champagne.",
    )),
    TimelineStep("Forty-five minutes in", listOf(
      "Read aloud: \"She left the ballroom at midnight with a Pink Lady in her hand. She did not reach her car. No one has heard from her since.\"",
    )),
    TimelineStep("Ninety minutes in", listOf(
      "Clue 1: the Bootlegger admits he saw her speak with someone on the lawn.",
    )),
    TimelineStep("Two hours in", listOf(
      "Clue 2: the Husband's alibi falls apart. He was not where he said.",
    )),
    TimelineStep("Two and a half hours", listOf(
      "Accusations.",
    )),
    TimelineStep("Three hours", listOf(
      "Reveal. Plate the chocolate-dipped strawberries. Pour the Champagne for the winner.",
    )),
  ),
  musicNote = "Dance jazz in the next room, audible but distant. Paul Whiteman, Original Memphis Five. When the clues come out, the music outside the room continues — that's the point.",
  playlistName = "West Egg, 1926",
  shoppingList = listOf(
    ShoppingItem("London Dry gin", "2 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Cognac", "1 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Applejack", "small", ShoppingAisle.Bar),
    ShoppingItem("Crème de cacao", "small", ShoppingAisle.Bar),
    ShoppingItem("Grenadine", "small", ShoppingAisle.Bar),
    ShoppingItem("Soda water", "2 × 1L", ShoppingAisle.Bar),
    ShoppingItem("Brut champagne", "3 × 750ml", ShoppingAisle.Bar),
    ShoppingItem("Lemons", "6", ShoppingAisle.Produce),
    ShoppingItem("Limes", "6", ShoppingAisle.Produce),
    ShoppingItem("Eggs", "4", ShoppingAisle.Dairy),
    ShoppingItem("Heavy cream", "1 pint", ShoppingAisle.Dairy),
    ShoppingItem("Whole nutmeg", "", ShoppingAisle.DryGoods),
    ShoppingItem("Caviar", "2 oz", ShoppingAisle.MeatFish),
    ShoppingItem("Buckwheat blinis", "10", ShoppingAisle.DryGoods),
    ShoppingItem("Crème fraîche", "8oz", ShoppingAisle.Dairy),
    ShoppingItem("Shallots", "3", ShoppingAisle.Produce),
    ShoppingItem("Chives", "1 bunch", ShoppingAisle.Produce),
    ShoppingItem("Oysters", "10", ShoppingAisle.MeatFish),
    ShoppingItem("Lobster tails", "3", ShoppingAisle.MeatFish),
    ShoppingItem("Beef tenderloin", "1 lb", ShoppingAisle.MeatFish),
    ShoppingItem("Watercress", "1 bunch", ShoppingAisle.Produce),
    ShoppingItem("Horseradish", "", ShoppingAisle.DryGoods),
    ShoppingItem("White button mushrooms", "12", ShoppingAisle.Produce),
    ShoppingItem("Crabmeat", "4oz", ShoppingAisle.MeatFish),
    ShoppingItem("Breadcrumbs", "", ShoppingAisle.DryGoods),
    ShoppingItem("Strawberries", "10 large", ShoppingAisle.Produce),
    ShoppingItem("Dark chocolate", "8oz", ShoppingAisle.DryGoods),
    ShoppingItem("Baguettes", "2 loaves", ShoppingAisle.DryGoods),
  ),
  shoppingTotal = "Roughly $295 for five guests, excluding the spirits. The caviar and lobster are the Long Island commitment.",
  faithfulNote = "Paddlefish caviar in place of osetra is a save of about $90. Vegetarian guests get mushroom pâté and tomato-jam crostini. The Pink Lady can step out with the egg white omitted for the raw-egg-shy.",
  citation = "Sourced from F. Scott Fitzgerald's *The Great Gatsby* (1925) for the named drinks and the Long Island estate party register, Albert Stevens Crockett's *Old Waldorf Bar Days* (1931) for the Brandy Alexander, and the Newport Yacht Club archive of estate-party menus 1924-1928.",
  isMystery = true,
  mysteryHook = "She left the ballroom at midnight with a Pink Lady in her hand. She did not reach her car. No one has heard from her since. The five of you are the only ones who saw her in the last hour. The host has gathered you in the library. Tell him what you know.",
  cast = listOf(
    MysteryCharacter(
      name = "The Host",
      role = "A West Egg newcomer. Throws Saturday parties. Was once in love with the vanished socialite. Insists it was years ago.",
      secret = "She had agreed to leave with you tonight before the party. She did not show up to the agreed meeting point on the lawn.",
    ),
    MysteryCharacter(
      name = "The Husband",
      role = "Married to the vanished socialite. Said he was in the smoking room from eleven to midnight. Cool and irritated.",
      secret = "You were on the lawn from eleven thirty to midnight. You saw your wife with someone. You did not approach.",
    ),
    MysteryCharacter(
      name = "The Bootlegger",
      role = "Delivered the champagne. Was loading the truck behind the kitchen at midnight. Saw the lawn from his vantage point.",
      secret = "You saw the vanished socialite speak with the Husband at eleven forty. You saw her walk away from him alive.",
    ),
    MysteryCharacter(
      name = "The Journalist",
      role = "Was at the party to write a profile of the Host. Has been following him for weeks. Carries a notebook he refuses to share.",
      secret = "Your notebook contains a draft of a story that implicates the Host in something the Husband does not yet know.",
    ),
    MysteryCharacter(
      name = "The Sister",
      role = "The vanished socialite's sister. Came late. Was sober. Has known something for months and has not said.",
      secret = "Your sister had been planning to disappear tonight. She left a note in the powder room before midnight. You found it at twelve fifteen.",
    ),
  ),
  mysteryReveal = "The socialite vanished by her own choice, with help. The Sister knew. The note in the powder room was her instruction to the Host to wait at the lawn rendezvous and the goodbye to her sister. The Husband saw her speak to the Host but read the moment wrong. The Bootlegger saw her walk away from her husband alive. The Journalist's draft about the Host was the leverage she used to extract help. She is not dead. She is somewhere else by morning.",
  hostPlaybook = "Clue 1 (forty-five minutes in): the Bootlegger volunteers he saw her speak to the Husband on the lawn. Clue 2 (ninety minutes in): the Husband's smoking-room alibi falls apart. Clue 3 (two hours in): the Sister produces the note. The reveal lands when guests realize this is a vanishing story, not a murder story.",
)

/** The five mystery menus, in canonical order. */
val MYSTERY_MENUS: List<PartyMenu> = listOf(
  MENU_MURDER_ALGONQUIN,
  MENU_BOOTLEGGERS_WIFE,
  MENU_LAST_TOAST_RITZ,
  MENU_HEIR_PENDENNIS,
  MENU_VANISHING_SOCIALITE,
)
